function out = model
%
% temp.m
%
% Model exported on Feb 17 2020, 20:15 by COMSOL 5.5.0.292.

import com.comsol.model.*
import com.comsol.model.util.*

model = ModelUtil.create('Model');

model.modelPath('E:\Work\Energiakaivos\Code');

model.label('temp.mph');

model.param.set('q_geothermal', '40[mW/m^2]');
model.param.set('T_surface', '2.3[degC]');
model.param.set('k_rock', '3[W/(m*K)]');
model.param.set('Cp_rock', '750[J/(kg*K)]');
model.param.set('rho_rock', '2700[kg/m^3]');
model.param.set('T_charge', '30[degC]');
model.param.set('Q_discharge', '1[MW]');

model.component.create('component', true);

model.component('component').geom.create('geometry', 3);

model.func.create('initial_temperature_function', 'Analytic');
model.func('initial_temperature_function').label('Initial Temperature Function');
model.func('initial_temperature_function').set('funcname', 'T_initial');
model.func('initial_temperature_function').set('expr', 'T_surface-q_geothermal/k_rock*z');
model.func('initial_temperature_function').set('args', {'z'});
model.func('initial_temperature_function').set('argunit', 'm');
model.func('initial_temperature_function').set('fununit', 'K');
model.func('initial_temperature_function').set('plotargs', {'z' '0' '1'});

model.component('component').mesh.create('mesh');

model.component('component').geom('geometry').create('work_plane_cbhe_structure1', 'WorkPlane');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure1').label('Work Plane for CBHE Structure 1');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure1').set('planetype', 'normalvector');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure1').set('normalvector', {'0.173648' '0.000000' '-0.984808'});
model.component('component').geom('geometry').feature('work_plane_cbhe_structure1').set('normalcoord', {'5.209445' '0.000000' '-129.544233'});
model.component('component').geom('geometry').feature('work_plane_cbhe_structure1').set('unite', true);
model.component('component').geom('geometry').feature('work_plane_cbhe_structure1').geom.create('circle1', 'Circle');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure1').geom.create('circle2', 'Circle');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure1').geom.feature('circle2').set('r', 0.038);
model.component('component').geom('geometry').feature('work_plane_cbhe_structure1').geom.create('circle3', 'Circle');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure1').geom.feature('circle3').set('r', 0.025);
model.component('component').geom('geometry').feature('work_plane_cbhe_structure1').geom.create('circle4', 'Circle');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure1').geom.feature('circle4').set('r', 0.016);
model.component('component').geom('geometry').feature('work_plane_cbhe_structure1').geom.create('polygon1', 'Polygon');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure1').geom.feature('polygon1').set('source', 'table');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure1').geom.feature('polygon1').set('table', {'1.000000' '0.000000'; '1.000000' '-1.000000'; '-1.000000' '-1.000000'; '-1.000000' '-0.000000'});
model.component('component').geom('geometry').feature('work_plane_cbhe_structure1').geom.create('difference', 'Difference');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure1').geom.feature('difference').selection('input').set({'circle1' 'circle2' 'circle3' 'circle4'});
model.component('component').geom('geometry').feature('work_plane_cbhe_structure1').geom.feature('difference').selection('input2').set({'polygon1'});
model.component('component').geom('geometry').create('extrusion_cbhe_structure1', 'Extrude');
model.component('component').geom('geometry').feature('extrusion_cbhe_structure1').label('Extrusion for CBHE Structure Work Plane 1');
model.component('component').geom('geometry').feature('extrusion_cbhe_structure1').setIndex('distance', '300', 0);
model.component('component').geom('geometry').feature('extrusion_cbhe_structure1').selection('input').set({'work_plane_cbhe_structure1'});
model.component('component').geom('geometry').create('work_plane_upper_cylinder1', 'WorkPlane');
model.component('component').geom('geometry').feature('work_plane_upper_cylinder1').label('Work Plane for Upper Cylinder 1');
model.component('component').geom('geometry').feature('work_plane_upper_cylinder1').set('planetype', 'normalvector');
model.component('component').geom('geometry').feature('work_plane_upper_cylinder1').set('normalvector', {'0.173648' '0.000000' '-0.984808'});
model.component('component').geom('geometry').feature('work_plane_upper_cylinder1').set('normalcoord', {'5.035797' '0.000000' '-128.559425'});
model.component('component').geom('geometry').feature('work_plane_upper_cylinder1').set('unite', true);
model.component('component').geom('geometry').feature('work_plane_upper_cylinder1').geom.create('circle1', 'Circle');
model.component('component').geom('geometry').feature('work_plane_upper_cylinder1').geom.create('polygon1', 'Polygon');
model.component('component').geom('geometry').feature('work_plane_upper_cylinder1').geom.feature('polygon1').set('source', 'table');
model.component('component').geom('geometry').feature('work_plane_upper_cylinder1').geom.feature('polygon1').set('table', {'1.000000' '0.000000'; '1.000000' '-1.000000'; '-1.000000' '-1.000000'; '-1.000000' '-0.000000'});
model.component('component').geom('geometry').feature('work_plane_upper_cylinder1').geom.create('difference', 'Difference');
model.component('component').geom('geometry').feature('work_plane_upper_cylinder1').geom.feature('difference').selection('input').set({'circle1'});
model.component('component').geom('geometry').feature('work_plane_upper_cylinder1').geom.feature('difference').selection('input2').set({'polygon1'});
model.component('component').geom('geometry').create('extrusion_upper_cylinder1', 'Extrude');
model.component('component').geom('geometry').feature('extrusion_upper_cylinder1').label('Extrusion for Upper Cylinder Work Plane 1');
model.component('component').geom('geometry').feature('extrusion_upper_cylinder1').selection('input').set({'work_plane_upper_cylinder1'});
model.component('component').geom('geometry').create('work_plane_lower_cylinder1', 'WorkPlane');
model.component('component').geom('geometry').feature('work_plane_lower_cylinder1').label('Work Plane for Lower Cylinder 1');
model.component('component').geom('geometry').feature('work_plane_lower_cylinder1').set('planetype', 'normalvector');
model.component('component').geom('geometry').feature('work_plane_lower_cylinder1').set('normalvector', {'0.173648' '0.000000' '-0.984808'});
model.component('component').geom('geometry').feature('work_plane_lower_cylinder1').set('normalcoord', {'57.303899' '0.000000' '-424.986558'});
model.component('component').geom('geometry').feature('work_plane_lower_cylinder1').set('unite', true);
model.component('component').geom('geometry').feature('work_plane_lower_cylinder1').geom.create('circle1', 'Circle');
model.component('component').geom('geometry').feature('work_plane_lower_cylinder1').geom.create('polygon1', 'Polygon');
model.component('component').geom('geometry').feature('work_plane_lower_cylinder1').geom.feature('polygon1').set('source', 'table');
model.component('component').geom('geometry').feature('work_plane_lower_cylinder1').geom.feature('polygon1').set('table', {'1.000000' '0.000000'; '1.000000' '-1.000000'; '-1.000000' '-1.000000'; '-1.000000' '-0.000000'});
model.component('component').geom('geometry').feature('work_plane_lower_cylinder1').geom.create('difference', 'Difference');
model.component('component').geom('geometry').feature('work_plane_lower_cylinder1').geom.feature('difference').selection('input').set({'circle1'});
model.component('component').geom('geometry').feature('work_plane_lower_cylinder1').geom.feature('difference').selection('input2').set({'polygon1'});
model.component('component').geom('geometry').create('extrusion_lower_cylinder1', 'Extrude');
model.component('component').geom('geometry').feature('extrusion_lower_cylinder1').label('Extrusion for Lower Cylinder Work Plane 1');
model.component('component').geom('geometry').feature('extrusion_lower_cylinder1').selection('input').set({'work_plane_lower_cylinder1'});
model.component('component').geom('geometry').create('work_plane_cbhe_structure2', 'WorkPlane');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure2').label('Work Plane for CBHE Structure 2');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure2').set('planetype', 'normalvector');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure2').set('normalvector', {'0.707107' '0.000000' '-0.707107'});
model.component('component').geom('geometry').feature('work_plane_cbhe_structure2').set('normalcoord', {'21.213203' '0.000000' '-121.213203'});
model.component('component').geom('geometry').feature('work_plane_cbhe_structure2').set('unite', true);
model.component('component').geom('geometry').feature('work_plane_cbhe_structure2').geom.create('circle1', 'Circle');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure2').geom.create('circle2', 'Circle');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure2').geom.feature('circle2').set('r', 0.038);
model.component('component').geom('geometry').feature('work_plane_cbhe_structure2').geom.create('circle3', 'Circle');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure2').geom.feature('circle3').set('r', 0.025);
model.component('component').geom('geometry').feature('work_plane_cbhe_structure2').geom.create('circle4', 'Circle');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure2').geom.feature('circle4').set('r', 0.016);
model.component('component').geom('geometry').feature('work_plane_cbhe_structure2').geom.create('polygon1', 'Polygon');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure2').geom.feature('polygon1').set('source', 'table');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure2').geom.feature('polygon1').set('table', {'1.000000' '0.000000'; '1.000000' '-1.000000'; '-1.000000' '-1.000000'; '-1.000000' '-0.000000'});
model.component('component').geom('geometry').feature('work_plane_cbhe_structure2').geom.create('difference', 'Difference');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure2').geom.feature('difference').selection('input').set({'circle1' 'circle2' 'circle3' 'circle4'});
model.component('component').geom('geometry').feature('work_plane_cbhe_structure2').geom.feature('difference').selection('input2').set({'polygon1'});
model.component('component').geom('geometry').create('extrusion_cbhe_structure2', 'Extrude');
model.component('component').geom('geometry').feature('extrusion_cbhe_structure2').label('Extrusion for CBHE Structure Work Plane 2');
model.component('component').geom('geometry').feature('extrusion_cbhe_structure2').setIndex('distance', '300', 0);
model.component('component').geom('geometry').feature('extrusion_cbhe_structure2').selection('input').set({'work_plane_cbhe_structure2'});
model.component('component').geom('geometry').create('work_plane_upper_cylinder2', 'WorkPlane');
model.component('component').geom('geometry').feature('work_plane_upper_cylinder2').label('Work Plane for Upper Cylinder 2');
model.component('component').geom('geometry').feature('work_plane_upper_cylinder2').set('planetype', 'normalvector');
model.component('component').geom('geometry').feature('work_plane_upper_cylinder2').set('normalvector', {'0.707107' '0.000000' '-0.707107'});
model.component('component').geom('geometry').feature('work_plane_upper_cylinder2').set('normalcoord', {'20.506097' '0.000000' '-120.506097'});
model.component('component').geom('geometry').feature('work_plane_upper_cylinder2').set('unite', true);
model.component('component').geom('geometry').feature('work_plane_upper_cylinder2').geom.create('circle1', 'Circle');
model.component('component').geom('geometry').feature('work_plane_upper_cylinder2').geom.create('polygon1', 'Polygon');
model.component('component').geom('geometry').feature('work_plane_upper_cylinder2').geom.feature('polygon1').set('source', 'table');
model.component('component').geom('geometry').feature('work_plane_upper_cylinder2').geom.feature('polygon1').set('table', {'1.000000' '0.000000'; '1.000000' '-1.000000'; '-1.000000' '-1.000000'; '-1.000000' '-0.000000'});
model.component('component').geom('geometry').feature('work_plane_upper_cylinder2').geom.create('difference', 'Difference');
model.component('component').geom('geometry').feature('work_plane_upper_cylinder2').geom.feature('difference').selection('input').set({'circle1'});
model.component('component').geom('geometry').feature('work_plane_upper_cylinder2').geom.feature('difference').selection('input2').set({'polygon1'});
model.component('component').geom('geometry').create('extrusion_upper_cylinder2', 'Extrude');
model.component('component').geom('geometry').feature('extrusion_upper_cylinder2').label('Extrusion for Upper Cylinder Work Plane 2');
model.component('component').geom('geometry').feature('extrusion_upper_cylinder2').selection('input').set({'work_plane_upper_cylinder2'});
model.component('component').geom('geometry').create('work_plane_lower_cylinder2', 'WorkPlane');
model.component('component').geom('geometry').feature('work_plane_lower_cylinder2').label('Work Plane for Lower Cylinder 2');
model.component('component').geom('geometry').feature('work_plane_lower_cylinder2').set('planetype', 'normalvector');
model.component('component').geom('geometry').feature('work_plane_lower_cylinder2').set('normalvector', {'0.707107' '0.000000' '-0.707107'});
model.component('component').geom('geometry').feature('work_plane_lower_cylinder2').set('normalcoord', {'233.345238' '0.000000' '-333.345238'});
model.component('component').geom('geometry').feature('work_plane_lower_cylinder2').set('unite', true);
model.component('component').geom('geometry').feature('work_plane_lower_cylinder2').geom.create('circle1', 'Circle');
model.component('component').geom('geometry').feature('work_plane_lower_cylinder2').geom.create('polygon1', 'Polygon');
model.component('component').geom('geometry').feature('work_plane_lower_cylinder2').geom.feature('polygon1').set('source', 'table');
model.component('component').geom('geometry').feature('work_plane_lower_cylinder2').geom.feature('polygon1').set('table', {'1.000000' '0.000000'; '1.000000' '-1.000000'; '-1.000000' '-1.000000'; '-1.000000' '-0.000000'});
model.component('component').geom('geometry').feature('work_plane_lower_cylinder2').geom.create('difference', 'Difference');
model.component('component').geom('geometry').feature('work_plane_lower_cylinder2').geom.feature('difference').selection('input').set({'circle1'});
model.component('component').geom('geometry').feature('work_plane_lower_cylinder2').geom.feature('difference').selection('input2').set({'polygon1'});
model.component('component').geom('geometry').create('extrusion_lower_cylinder2', 'Extrude');
model.component('component').geom('geometry').feature('extrusion_lower_cylinder2').label('Extrusion for Lower Cylinder Work Plane 2');
model.component('component').geom('geometry').feature('extrusion_lower_cylinder2').selection('input').set({'work_plane_lower_cylinder2'});
model.component('component').geom('geometry').create('work_plane_cbhe_structure3', 'WorkPlane');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure3').label('Work Plane for CBHE Structure 3');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure3').set('planetype', 'normalvector');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure3').set('normalvector', {'1.000000' '0.000000' '0.000000'});
model.component('component').geom('geometry').feature('work_plane_cbhe_structure3').set('normalcoord', {'30.000000' '0.000000' '-100.000000'});
model.component('component').geom('geometry').feature('work_plane_cbhe_structure3').set('unite', true);
model.component('component').geom('geometry').feature('work_plane_cbhe_structure3').geom.create('circle1', 'Circle');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure3').geom.create('circle2', 'Circle');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure3').geom.feature('circle2').set('r', 0.038);
model.component('component').geom('geometry').feature('work_plane_cbhe_structure3').geom.create('circle3', 'Circle');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure3').geom.feature('circle3').set('r', 0.025);
model.component('component').geom('geometry').feature('work_plane_cbhe_structure3').geom.create('circle4', 'Circle');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure3').geom.feature('circle4').set('r', 0.016);
model.component('component').geom('geometry').feature('work_plane_cbhe_structure3').geom.create('polygon1', 'Polygon');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure3').geom.feature('polygon1').set('source', 'table');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure3').geom.feature('polygon1').set('table', {'1.000000' '0.000000'; '1.000000' '-1.000000'; '-1.000000' '-1.000000'; '-1.000000' '-0.000000'});
model.component('component').geom('geometry').feature('work_plane_cbhe_structure3').geom.create('difference', 'Difference');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure3').geom.feature('difference').selection('input').set({'circle1' 'circle2' 'circle3' 'circle4'});
model.component('component').geom('geometry').feature('work_plane_cbhe_structure3').geom.feature('difference').selection('input2').set({'polygon1'});
model.component('component').geom('geometry').create('extrusion_cbhe_structure3', 'Extrude');
model.component('component').geom('geometry').feature('extrusion_cbhe_structure3').label('Extrusion for CBHE Structure Work Plane 3');
model.component('component').geom('geometry').feature('extrusion_cbhe_structure3').setIndex('distance', '300', 0);
model.component('component').geom('geometry').feature('extrusion_cbhe_structure3').selection('input').set({'work_plane_cbhe_structure3'});
model.component('component').geom('geometry').create('work_plane_upper_cylinder3', 'WorkPlane');
model.component('component').geom('geometry').feature('work_plane_upper_cylinder3').label('Work Plane for Upper Cylinder 3');
model.component('component').geom('geometry').feature('work_plane_upper_cylinder3').set('planetype', 'normalvector');
model.component('component').geom('geometry').feature('work_plane_upper_cylinder3').set('normalvector', {'1.000000' '0.000000' '0.000000'});
model.component('component').geom('geometry').feature('work_plane_upper_cylinder3').set('normalcoord', {'29.000000' '0.000000' '-100.000000'});
model.component('component').geom('geometry').feature('work_plane_upper_cylinder3').set('unite', true);
model.component('component').geom('geometry').feature('work_plane_upper_cylinder3').geom.create('circle1', 'Circle');
model.component('component').geom('geometry').feature('work_plane_upper_cylinder3').geom.create('polygon1', 'Polygon');
model.component('component').geom('geometry').feature('work_plane_upper_cylinder3').geom.feature('polygon1').set('source', 'table');
model.component('component').geom('geometry').feature('work_plane_upper_cylinder3').geom.feature('polygon1').set('table', {'1.000000' '0.000000'; '1.000000' '-1.000000'; '-1.000000' '-1.000000'; '-1.000000' '-0.000000'});
model.component('component').geom('geometry').feature('work_plane_upper_cylinder3').geom.create('difference', 'Difference');
model.component('component').geom('geometry').feature('work_plane_upper_cylinder3').geom.feature('difference').selection('input').set({'circle1'});
model.component('component').geom('geometry').feature('work_plane_upper_cylinder3').geom.feature('difference').selection('input2').set({'polygon1'});
model.component('component').geom('geometry').create('extrusion_upper_cylinder3', 'Extrude');
model.component('component').geom('geometry').feature('extrusion_upper_cylinder3').label('Extrusion for Upper Cylinder Work Plane 3');
model.component('component').geom('geometry').feature('extrusion_upper_cylinder3').selection('input').set({'work_plane_upper_cylinder3'});
model.component('component').geom('geometry').create('work_plane_lower_cylinder3', 'WorkPlane');
model.component('component').geom('geometry').feature('work_plane_lower_cylinder3').label('Work Plane for Lower Cylinder 3');
model.component('component').geom('geometry').feature('work_plane_lower_cylinder3').set('planetype', 'normalvector');
model.component('component').geom('geometry').feature('work_plane_lower_cylinder3').set('normalvector', {'1.000000' '0.000000' '0.000000'});
model.component('component').geom('geometry').feature('work_plane_lower_cylinder3').set('normalcoord', {'330.000000' '0.000000' '-100.000000'});
model.component('component').geom('geometry').feature('work_plane_lower_cylinder3').set('unite', true);
model.component('component').geom('geometry').feature('work_plane_lower_cylinder3').geom.create('circle1', 'Circle');
model.component('component').geom('geometry').feature('work_plane_lower_cylinder3').geom.create('polygon1', 'Polygon');
model.component('component').geom('geometry').feature('work_plane_lower_cylinder3').geom.feature('polygon1').set('source', 'table');
model.component('component').geom('geometry').feature('work_plane_lower_cylinder3').geom.feature('polygon1').set('table', {'1.000000' '0.000000'; '1.000000' '-1.000000'; '-1.000000' '-1.000000'; '-1.000000' '-0.000000'});
model.component('component').geom('geometry').feature('work_plane_lower_cylinder3').geom.create('difference', 'Difference');
model.component('component').geom('geometry').feature('work_plane_lower_cylinder3').geom.feature('difference').selection('input').set({'circle1'});
model.component('component').geom('geometry').feature('work_plane_lower_cylinder3').geom.feature('difference').selection('input2').set({'polygon1'});
model.component('component').geom('geometry').create('extrusion_lower_cylinder3', 'Extrude');
model.component('component').geom('geometry').feature('extrusion_lower_cylinder3').label('Extrusion for Lower Cylinder Work Plane 3');
model.component('component').geom('geometry').feature('extrusion_lower_cylinder3').selection('input').set({'work_plane_lower_cylinder3'});
model.component('component').geom('geometry').create('work_plane_cbhe_structure4', 'WorkPlane');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure4').label('Work Plane for CBHE Structure 4');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure4').set('planetype', 'normalvector');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure4').set('normalvector', {'0.173648' '0.000000' '-0.984808'});
model.component('component').geom('geometry').feature('work_plane_cbhe_structure4').set('normalcoord', {'5.209445' '20.000000' '-129.544233'});
model.component('component').geom('geometry').feature('work_plane_cbhe_structure4').set('unite', true);
model.component('component').geom('geometry').feature('work_plane_cbhe_structure4').geom.create('circle1', 'Circle');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure4').geom.create('circle2', 'Circle');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure4').geom.feature('circle2').set('r', 0.038);
model.component('component').geom('geometry').feature('work_plane_cbhe_structure4').geom.create('circle3', 'Circle');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure4').geom.feature('circle3').set('r', 0.025);
model.component('component').geom('geometry').feature('work_plane_cbhe_structure4').geom.create('circle4', 'Circle');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure4').geom.feature('circle4').set('r', 0.016);
model.component('component').geom('geometry').create('extrusion_cbhe_structure4', 'Extrude');
model.component('component').geom('geometry').feature('extrusion_cbhe_structure4').label('Extrusion for CBHE Structure Work Plane 4');
model.component('component').geom('geometry').feature('extrusion_cbhe_structure4').setIndex('distance', '300', 0);
model.component('component').geom('geometry').feature('extrusion_cbhe_structure4').selection('input').set({'work_plane_cbhe_structure4'});
model.component('component').geom('geometry').create('work_plane_upper_cylinder4', 'WorkPlane');
model.component('component').geom('geometry').feature('work_plane_upper_cylinder4').label('Work Plane for Upper Cylinder 4');
model.component('component').geom('geometry').feature('work_plane_upper_cylinder4').set('planetype', 'normalvector');
model.component('component').geom('geometry').feature('work_plane_upper_cylinder4').set('normalvector', {'0.173648' '0.000000' '-0.984808'});
model.component('component').geom('geometry').feature('work_plane_upper_cylinder4').set('normalcoord', {'5.035797' '20.000000' '-128.559425'});
model.component('component').geom('geometry').feature('work_plane_upper_cylinder4').set('unite', true);
model.component('component').geom('geometry').feature('work_plane_upper_cylinder4').geom.create('circle1', 'Circle');
model.component('component').geom('geometry').create('extrusion_upper_cylinder4', 'Extrude');
model.component('component').geom('geometry').feature('extrusion_upper_cylinder4').label('Extrusion for Upper Cylinder Work Plane 4');
model.component('component').geom('geometry').feature('extrusion_upper_cylinder4').selection('input').set({'work_plane_upper_cylinder4'});
model.component('component').geom('geometry').create('work_plane_lower_cylinder4', 'WorkPlane');
model.component('component').geom('geometry').feature('work_plane_lower_cylinder4').label('Work Plane for Lower Cylinder 4');
model.component('component').geom('geometry').feature('work_plane_lower_cylinder4').set('planetype', 'normalvector');
model.component('component').geom('geometry').feature('work_plane_lower_cylinder4').set('normalvector', {'0.173648' '0.000000' '-0.984808'});
model.component('component').geom('geometry').feature('work_plane_lower_cylinder4').set('normalcoord', {'57.303899' '20.000000' '-424.986558'});
model.component('component').geom('geometry').feature('work_plane_lower_cylinder4').set('unite', true);
model.component('component').geom('geometry').feature('work_plane_lower_cylinder4').geom.create('circle1', 'Circle');
model.component('component').geom('geometry').create('extrusion_lower_cylinder4', 'Extrude');
model.component('component').geom('geometry').feature('extrusion_lower_cylinder4').label('Extrusion for Lower Cylinder Work Plane 4');
model.component('component').geom('geometry').feature('extrusion_lower_cylinder4').selection('input').set({'work_plane_lower_cylinder4'});
model.component('component').geom('geometry').create('work_plane_cbhe_structure5', 'WorkPlane');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure5').label('Work Plane for CBHE Structure 5');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure5').set('planetype', 'normalvector');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure5').set('normalvector', {'0.707107' '0.000000' '-0.707107'});
model.component('component').geom('geometry').feature('work_plane_cbhe_structure5').set('normalcoord', {'21.213203' '20.000000' '-121.213203'});
model.component('component').geom('geometry').feature('work_plane_cbhe_structure5').set('unite', true);
model.component('component').geom('geometry').feature('work_plane_cbhe_structure5').geom.create('circle1', 'Circle');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure5').geom.create('circle2', 'Circle');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure5').geom.feature('circle2').set('r', 0.038);
model.component('component').geom('geometry').feature('work_plane_cbhe_structure5').geom.create('circle3', 'Circle');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure5').geom.feature('circle3').set('r', 0.025);
model.component('component').geom('geometry').feature('work_plane_cbhe_structure5').geom.create('circle4', 'Circle');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure5').geom.feature('circle4').set('r', 0.016);
model.component('component').geom('geometry').create('extrusion_cbhe_structure5', 'Extrude');
model.component('component').geom('geometry').feature('extrusion_cbhe_structure5').label('Extrusion for CBHE Structure Work Plane 5');
model.component('component').geom('geometry').feature('extrusion_cbhe_structure5').setIndex('distance', '300', 0);
model.component('component').geom('geometry').feature('extrusion_cbhe_structure5').selection('input').set({'work_plane_cbhe_structure5'});
model.component('component').geom('geometry').create('work_plane_upper_cylinder5', 'WorkPlane');
model.component('component').geom('geometry').feature('work_plane_upper_cylinder5').label('Work Plane for Upper Cylinder 5');
model.component('component').geom('geometry').feature('work_plane_upper_cylinder5').set('planetype', 'normalvector');
model.component('component').geom('geometry').feature('work_plane_upper_cylinder5').set('normalvector', {'0.707107' '0.000000' '-0.707107'});
model.component('component').geom('geometry').feature('work_plane_upper_cylinder5').set('normalcoord', {'20.506097' '20.000000' '-120.506097'});
model.component('component').geom('geometry').feature('work_plane_upper_cylinder5').set('unite', true);
model.component('component').geom('geometry').feature('work_plane_upper_cylinder5').geom.create('circle1', 'Circle');
model.component('component').geom('geometry').create('extrusion_upper_cylinder5', 'Extrude');
model.component('component').geom('geometry').feature('extrusion_upper_cylinder5').label('Extrusion for Upper Cylinder Work Plane 5');
model.component('component').geom('geometry').feature('extrusion_upper_cylinder5').selection('input').set({'work_plane_upper_cylinder5'});
model.component('component').geom('geometry').create('work_plane_lower_cylinder5', 'WorkPlane');
model.component('component').geom('geometry').feature('work_plane_lower_cylinder5').label('Work Plane for Lower Cylinder 5');
model.component('component').geom('geometry').feature('work_plane_lower_cylinder5').set('planetype', 'normalvector');
model.component('component').geom('geometry').feature('work_plane_lower_cylinder5').set('normalvector', {'0.707107' '0.000000' '-0.707107'});
model.component('component').geom('geometry').feature('work_plane_lower_cylinder5').set('normalcoord', {'233.345238' '20.000000' '-333.345238'});
model.component('component').geom('geometry').feature('work_plane_lower_cylinder5').set('unite', true);
model.component('component').geom('geometry').feature('work_plane_lower_cylinder5').geom.create('circle1', 'Circle');
model.component('component').geom('geometry').create('extrusion_lower_cylinder5', 'Extrude');
model.component('component').geom('geometry').feature('extrusion_lower_cylinder5').label('Extrusion for Lower Cylinder Work Plane 5');
model.component('component').geom('geometry').feature('extrusion_lower_cylinder5').selection('input').set({'work_plane_lower_cylinder5'});
model.component('component').geom('geometry').create('work_plane_cbhe_structure6', 'WorkPlane');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure6').label('Work Plane for CBHE Structure 6');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure6').set('planetype', 'normalvector');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure6').set('normalvector', {'1.000000' '0.000000' '0.000000'});
model.component('component').geom('geometry').feature('work_plane_cbhe_structure6').set('normalcoord', {'30.000000' '20.000000' '-100.000000'});
model.component('component').geom('geometry').feature('work_plane_cbhe_structure6').set('unite', true);
model.component('component').geom('geometry').feature('work_plane_cbhe_structure6').geom.create('circle1', 'Circle');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure6').geom.create('circle2', 'Circle');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure6').geom.feature('circle2').set('r', 0.038);
model.component('component').geom('geometry').feature('work_plane_cbhe_structure6').geom.create('circle3', 'Circle');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure6').geom.feature('circle3').set('r', 0.025);
model.component('component').geom('geometry').feature('work_plane_cbhe_structure6').geom.create('circle4', 'Circle');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure6').geom.feature('circle4').set('r', 0.016);
model.component('component').geom('geometry').create('extrusion_cbhe_structure6', 'Extrude');
model.component('component').geom('geometry').feature('extrusion_cbhe_structure6').label('Extrusion for CBHE Structure Work Plane 6');
model.component('component').geom('geometry').feature('extrusion_cbhe_structure6').setIndex('distance', '300', 0);
model.component('component').geom('geometry').feature('extrusion_cbhe_structure6').selection('input').set({'work_plane_cbhe_structure6'});
model.component('component').geom('geometry').create('work_plane_upper_cylinder6', 'WorkPlane');
model.component('component').geom('geometry').feature('work_plane_upper_cylinder6').label('Work Plane for Upper Cylinder 6');
model.component('component').geom('geometry').feature('work_plane_upper_cylinder6').set('planetype', 'normalvector');
model.component('component').geom('geometry').feature('work_plane_upper_cylinder6').set('normalvector', {'1.000000' '0.000000' '0.000000'});
model.component('component').geom('geometry').feature('work_plane_upper_cylinder6').set('normalcoord', {'29.000000' '20.000000' '-100.000000'});
model.component('component').geom('geometry').feature('work_plane_upper_cylinder6').set('unite', true);
model.component('component').geom('geometry').feature('work_plane_upper_cylinder6').geom.create('circle1', 'Circle');
model.component('component').geom('geometry').create('extrusion_upper_cylinder6', 'Extrude');
model.component('component').geom('geometry').feature('extrusion_upper_cylinder6').label('Extrusion for Upper Cylinder Work Plane 6');
model.component('component').geom('geometry').feature('extrusion_upper_cylinder6').selection('input').set({'work_plane_upper_cylinder6'});
model.component('component').geom('geometry').create('work_plane_lower_cylinder6', 'WorkPlane');
model.component('component').geom('geometry').feature('work_plane_lower_cylinder6').label('Work Plane for Lower Cylinder 6');
model.component('component').geom('geometry').feature('work_plane_lower_cylinder6').set('planetype', 'normalvector');
model.component('component').geom('geometry').feature('work_plane_lower_cylinder6').set('normalvector', {'1.000000' '0.000000' '0.000000'});
model.component('component').geom('geometry').feature('work_plane_lower_cylinder6').set('normalcoord', {'330.000000' '20.000000' '-100.000000'});
model.component('component').geom('geometry').feature('work_plane_lower_cylinder6').set('unite', true);
model.component('component').geom('geometry').feature('work_plane_lower_cylinder6').geom.create('circle1', 'Circle');
model.component('component').geom('geometry').create('extrusion_lower_cylinder6', 'Extrude');
model.component('component').geom('geometry').feature('extrusion_lower_cylinder6').label('Extrusion for Lower Cylinder Work Plane 6');
model.component('component').geom('geometry').feature('extrusion_lower_cylinder6').selection('input').set({'work_plane_lower_cylinder6'});
model.component('component').geom('geometry').create('work_plane_cbhe_structure7', 'WorkPlane');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure7').label('Work Plane for CBHE Structure 7');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure7').set('planetype', 'normalvector');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure7').set('normalvector', {'0.173648' '0.000000' '-0.984808'});
model.component('component').geom('geometry').feature('work_plane_cbhe_structure7').set('normalcoord', {'5.209445' '40.000000' '-129.544233'});
model.component('component').geom('geometry').feature('work_plane_cbhe_structure7').set('unite', true);
model.component('component').geom('geometry').feature('work_plane_cbhe_structure7').geom.create('circle1', 'Circle');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure7').geom.create('circle2', 'Circle');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure7').geom.feature('circle2').set('r', 0.038);
model.component('component').geom('geometry').feature('work_plane_cbhe_structure7').geom.create('circle3', 'Circle');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure7').geom.feature('circle3').set('r', 0.025);
model.component('component').geom('geometry').feature('work_plane_cbhe_structure7').geom.create('circle4', 'Circle');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure7').geom.feature('circle4').set('r', 0.016);
model.component('component').geom('geometry').create('extrusion_cbhe_structure7', 'Extrude');
model.component('component').geom('geometry').feature('extrusion_cbhe_structure7').label('Extrusion for CBHE Structure Work Plane 7');
model.component('component').geom('geometry').feature('extrusion_cbhe_structure7').setIndex('distance', '300', 0);
model.component('component').geom('geometry').feature('extrusion_cbhe_structure7').selection('input').set({'work_plane_cbhe_structure7'});
model.component('component').geom('geometry').create('work_plane_upper_cylinder7', 'WorkPlane');
model.component('component').geom('geometry').feature('work_plane_upper_cylinder7').label('Work Plane for Upper Cylinder 7');
model.component('component').geom('geometry').feature('work_plane_upper_cylinder7').set('planetype', 'normalvector');
model.component('component').geom('geometry').feature('work_plane_upper_cylinder7').set('normalvector', {'0.173648' '0.000000' '-0.984808'});
model.component('component').geom('geometry').feature('work_plane_upper_cylinder7').set('normalcoord', {'5.035797' '40.000000' '-128.559425'});
model.component('component').geom('geometry').feature('work_plane_upper_cylinder7').set('unite', true);
model.component('component').geom('geometry').feature('work_plane_upper_cylinder7').geom.create('circle1', 'Circle');
model.component('component').geom('geometry').create('extrusion_upper_cylinder7', 'Extrude');
model.component('component').geom('geometry').feature('extrusion_upper_cylinder7').label('Extrusion for Upper Cylinder Work Plane 7');
model.component('component').geom('geometry').feature('extrusion_upper_cylinder7').selection('input').set({'work_plane_upper_cylinder7'});
model.component('component').geom('geometry').create('work_plane_lower_cylinder7', 'WorkPlane');
model.component('component').geom('geometry').feature('work_plane_lower_cylinder7').label('Work Plane for Lower Cylinder 7');
model.component('component').geom('geometry').feature('work_plane_lower_cylinder7').set('planetype', 'normalvector');
model.component('component').geom('geometry').feature('work_plane_lower_cylinder7').set('normalvector', {'0.173648' '0.000000' '-0.984808'});
model.component('component').geom('geometry').feature('work_plane_lower_cylinder7').set('normalcoord', {'57.303899' '40.000000' '-424.986558'});
model.component('component').geom('geometry').feature('work_plane_lower_cylinder7').set('unite', true);
model.component('component').geom('geometry').feature('work_plane_lower_cylinder7').geom.create('circle1', 'Circle');
model.component('component').geom('geometry').create('extrusion_lower_cylinder7', 'Extrude');
model.component('component').geom('geometry').feature('extrusion_lower_cylinder7').label('Extrusion for Lower Cylinder Work Plane 7');
model.component('component').geom('geometry').feature('extrusion_lower_cylinder7').selection('input').set({'work_plane_lower_cylinder7'});
model.component('component').geom('geometry').create('work_plane_cbhe_structure8', 'WorkPlane');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure8').label('Work Plane for CBHE Structure 8');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure8').set('planetype', 'normalvector');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure8').set('normalvector', {'0.707107' '0.000000' '-0.707107'});
model.component('component').geom('geometry').feature('work_plane_cbhe_structure8').set('normalcoord', {'21.213203' '40.000000' '-121.213203'});
model.component('component').geom('geometry').feature('work_plane_cbhe_structure8').set('unite', true);
model.component('component').geom('geometry').feature('work_plane_cbhe_structure8').geom.create('circle1', 'Circle');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure8').geom.create('circle2', 'Circle');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure8').geom.feature('circle2').set('r', 0.038);
model.component('component').geom('geometry').feature('work_plane_cbhe_structure8').geom.create('circle3', 'Circle');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure8').geom.feature('circle3').set('r', 0.025);
model.component('component').geom('geometry').feature('work_plane_cbhe_structure8').geom.create('circle4', 'Circle');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure8').geom.feature('circle4').set('r', 0.016);
model.component('component').geom('geometry').create('extrusion_cbhe_structure8', 'Extrude');
model.component('component').geom('geometry').feature('extrusion_cbhe_structure8').label('Extrusion for CBHE Structure Work Plane 8');
model.component('component').geom('geometry').feature('extrusion_cbhe_structure8').setIndex('distance', '300', 0);
model.component('component').geom('geometry').feature('extrusion_cbhe_structure8').selection('input').set({'work_plane_cbhe_structure8'});
model.component('component').geom('geometry').create('work_plane_upper_cylinder8', 'WorkPlane');
model.component('component').geom('geometry').feature('work_plane_upper_cylinder8').label('Work Plane for Upper Cylinder 8');
model.component('component').geom('geometry').feature('work_plane_upper_cylinder8').set('planetype', 'normalvector');
model.component('component').geom('geometry').feature('work_plane_upper_cylinder8').set('normalvector', {'0.707107' '0.000000' '-0.707107'});
model.component('component').geom('geometry').feature('work_plane_upper_cylinder8').set('normalcoord', {'20.506097' '40.000000' '-120.506097'});
model.component('component').geom('geometry').feature('work_plane_upper_cylinder8').set('unite', true);
model.component('component').geom('geometry').feature('work_plane_upper_cylinder8').geom.create('circle1', 'Circle');
model.component('component').geom('geometry').create('extrusion_upper_cylinder8', 'Extrude');
model.component('component').geom('geometry').feature('extrusion_upper_cylinder8').label('Extrusion for Upper Cylinder Work Plane 8');
model.component('component').geom('geometry').feature('extrusion_upper_cylinder8').selection('input').set({'work_plane_upper_cylinder8'});
model.component('component').geom('geometry').create('work_plane_lower_cylinder8', 'WorkPlane');
model.component('component').geom('geometry').feature('work_plane_lower_cylinder8').label('Work Plane for Lower Cylinder 8');
model.component('component').geom('geometry').feature('work_plane_lower_cylinder8').set('planetype', 'normalvector');
model.component('component').geom('geometry').feature('work_plane_lower_cylinder8').set('normalvector', {'0.707107' '0.000000' '-0.707107'});
model.component('component').geom('geometry').feature('work_plane_lower_cylinder8').set('normalcoord', {'233.345238' '40.000000' '-333.345238'});
model.component('component').geom('geometry').feature('work_plane_lower_cylinder8').set('unite', true);
model.component('component').geom('geometry').feature('work_plane_lower_cylinder8').geom.create('circle1', 'Circle');
model.component('component').geom('geometry').create('extrusion_lower_cylinder8', 'Extrude');
model.component('component').geom('geometry').feature('extrusion_lower_cylinder8').label('Extrusion for Lower Cylinder Work Plane 8');
model.component('component').geom('geometry').feature('extrusion_lower_cylinder8').selection('input').set({'work_plane_lower_cylinder8'});
model.component('component').geom('geometry').create('work_plane_cbhe_structure9', 'WorkPlane');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure9').label('Work Plane for CBHE Structure 9');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure9').set('planetype', 'normalvector');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure9').set('normalvector', {'1.000000' '0.000000' '0.000000'});
model.component('component').geom('geometry').feature('work_plane_cbhe_structure9').set('normalcoord', {'30.000000' '40.000000' '-100.000000'});
model.component('component').geom('geometry').feature('work_plane_cbhe_structure9').set('unite', true);
model.component('component').geom('geometry').feature('work_plane_cbhe_structure9').geom.create('circle1', 'Circle');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure9').geom.create('circle2', 'Circle');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure9').geom.feature('circle2').set('r', 0.038);
model.component('component').geom('geometry').feature('work_plane_cbhe_structure9').geom.create('circle3', 'Circle');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure9').geom.feature('circle3').set('r', 0.025);
model.component('component').geom('geometry').feature('work_plane_cbhe_structure9').geom.create('circle4', 'Circle');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure9').geom.feature('circle4').set('r', 0.016);
model.component('component').geom('geometry').create('extrusion_cbhe_structure9', 'Extrude');
model.component('component').geom('geometry').feature('extrusion_cbhe_structure9').label('Extrusion for CBHE Structure Work Plane 9');
model.component('component').geom('geometry').feature('extrusion_cbhe_structure9').setIndex('distance', '300', 0);
model.component('component').geom('geometry').feature('extrusion_cbhe_structure9').selection('input').set({'work_plane_cbhe_structure9'});
model.component('component').geom('geometry').create('work_plane_upper_cylinder9', 'WorkPlane');
model.component('component').geom('geometry').feature('work_plane_upper_cylinder9').label('Work Plane for Upper Cylinder 9');
model.component('component').geom('geometry').feature('work_plane_upper_cylinder9').set('planetype', 'normalvector');
model.component('component').geom('geometry').feature('work_plane_upper_cylinder9').set('normalvector', {'1.000000' '0.000000' '0.000000'});
model.component('component').geom('geometry').feature('work_plane_upper_cylinder9').set('normalcoord', {'29.000000' '40.000000' '-100.000000'});
model.component('component').geom('geometry').feature('work_plane_upper_cylinder9').set('unite', true);
model.component('component').geom('geometry').feature('work_plane_upper_cylinder9').geom.create('circle1', 'Circle');
model.component('component').geom('geometry').create('extrusion_upper_cylinder9', 'Extrude');
model.component('component').geom('geometry').feature('extrusion_upper_cylinder9').label('Extrusion for Upper Cylinder Work Plane 9');
model.component('component').geom('geometry').feature('extrusion_upper_cylinder9').selection('input').set({'work_plane_upper_cylinder9'});
model.component('component').geom('geometry').create('work_plane_lower_cylinder9', 'WorkPlane');
model.component('component').geom('geometry').feature('work_plane_lower_cylinder9').label('Work Plane for Lower Cylinder 9');
model.component('component').geom('geometry').feature('work_plane_lower_cylinder9').set('planetype', 'normalvector');
model.component('component').geom('geometry').feature('work_plane_lower_cylinder9').set('normalvector', {'1.000000' '0.000000' '0.000000'});
model.component('component').geom('geometry').feature('work_plane_lower_cylinder9').set('normalcoord', {'330.000000' '40.000000' '-100.000000'});
model.component('component').geom('geometry').feature('work_plane_lower_cylinder9').set('unite', true);
model.component('component').geom('geometry').feature('work_plane_lower_cylinder9').geom.create('circle1', 'Circle');
model.component('component').geom('geometry').create('extrusion_lower_cylinder9', 'Extrude');
model.component('component').geom('geometry').feature('extrusion_lower_cylinder9').label('Extrusion for Lower Cylinder Work Plane 9');
model.component('component').geom('geometry').feature('extrusion_lower_cylinder9').selection('input').set({'work_plane_lower_cylinder9'});
model.component('component').geom('geometry').create('work_plane_cbhe_structure10', 'WorkPlane');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure10').label('Work Plane for CBHE Structure 10');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure10').set('planetype', 'normalvector');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure10').set('normalvector', {'0.173648' '0.000000' '-0.984808'});
model.component('component').geom('geometry').feature('work_plane_cbhe_structure10').set('normalcoord', {'5.209445' '60.000000' '-129.544233'});
model.component('component').geom('geometry').feature('work_plane_cbhe_structure10').set('unite', true);
model.component('component').geom('geometry').feature('work_plane_cbhe_structure10').geom.create('circle1', 'Circle');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure10').geom.create('circle2', 'Circle');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure10').geom.feature('circle2').set('r', 0.038);
model.component('component').geom('geometry').feature('work_plane_cbhe_structure10').geom.create('circle3', 'Circle');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure10').geom.feature('circle3').set('r', 0.025);
model.component('component').geom('geometry').feature('work_plane_cbhe_structure10').geom.create('circle4', 'Circle');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure10').geom.feature('circle4').set('r', 0.016);
model.component('component').geom('geometry').create('extrusion_cbhe_structure10', 'Extrude');
model.component('component').geom('geometry').feature('extrusion_cbhe_structure10').label('Extrusion for CBHE Structure Work Plane 10');
model.component('component').geom('geometry').feature('extrusion_cbhe_structure10').setIndex('distance', '300', 0);
model.component('component').geom('geometry').feature('extrusion_cbhe_structure10').selection('input').set({'work_plane_cbhe_structure10'});
model.component('component').geom('geometry').create('work_plane_upper_cylinder10', 'WorkPlane');
model.component('component').geom('geometry').feature('work_plane_upper_cylinder10').label('Work Plane for Upper Cylinder 10');
model.component('component').geom('geometry').feature('work_plane_upper_cylinder10').set('planetype', 'normalvector');
model.component('component').geom('geometry').feature('work_plane_upper_cylinder10').set('normalvector', {'0.173648' '0.000000' '-0.984808'});
model.component('component').geom('geometry').feature('work_plane_upper_cylinder10').set('normalcoord', {'5.035797' '60.000000' '-128.559425'});
model.component('component').geom('geometry').feature('work_plane_upper_cylinder10').set('unite', true);
model.component('component').geom('geometry').feature('work_plane_upper_cylinder10').geom.create('circle1', 'Circle');
model.component('component').geom('geometry').create('extrusion_upper_cylinder10', 'Extrude');
model.component('component').geom('geometry').feature('extrusion_upper_cylinder10').label('Extrusion for Upper Cylinder Work Plane 10');
model.component('component').geom('geometry').feature('extrusion_upper_cylinder10').selection('input').set({'work_plane_upper_cylinder10'});
model.component('component').geom('geometry').create('work_plane_lower_cylinder10', 'WorkPlane');
model.component('component').geom('geometry').feature('work_plane_lower_cylinder10').label('Work Plane for Lower Cylinder 10');
model.component('component').geom('geometry').feature('work_plane_lower_cylinder10').set('planetype', 'normalvector');
model.component('component').geom('geometry').feature('work_plane_lower_cylinder10').set('normalvector', {'0.173648' '0.000000' '-0.984808'});
model.component('component').geom('geometry').feature('work_plane_lower_cylinder10').set('normalcoord', {'57.303899' '60.000000' '-424.986558'});
model.component('component').geom('geometry').feature('work_plane_lower_cylinder10').set('unite', true);
model.component('component').geom('geometry').feature('work_plane_lower_cylinder10').geom.create('circle1', 'Circle');
model.component('component').geom('geometry').create('extrusion_lower_cylinder10', 'Extrude');
model.component('component').geom('geometry').feature('extrusion_lower_cylinder10').label('Extrusion for Lower Cylinder Work Plane 10');
model.component('component').geom('geometry').feature('extrusion_lower_cylinder10').selection('input').set({'work_plane_lower_cylinder10'});
model.component('component').geom('geometry').create('work_plane_cbhe_structure11', 'WorkPlane');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure11').label('Work Plane for CBHE Structure 11');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure11').set('planetype', 'normalvector');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure11').set('normalvector', {'0.707107' '0.000000' '-0.707107'});
model.component('component').geom('geometry').feature('work_plane_cbhe_structure11').set('normalcoord', {'21.213203' '60.000000' '-121.213203'});
model.component('component').geom('geometry').feature('work_plane_cbhe_structure11').set('unite', true);
model.component('component').geom('geometry').feature('work_plane_cbhe_structure11').geom.create('circle1', 'Circle');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure11').geom.create('circle2', 'Circle');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure11').geom.feature('circle2').set('r', 0.038);
model.component('component').geom('geometry').feature('work_plane_cbhe_structure11').geom.create('circle3', 'Circle');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure11').geom.feature('circle3').set('r', 0.025);
model.component('component').geom('geometry').feature('work_plane_cbhe_structure11').geom.create('circle4', 'Circle');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure11').geom.feature('circle4').set('r', 0.016);
model.component('component').geom('geometry').create('extrusion_cbhe_structure11', 'Extrude');
model.component('component').geom('geometry').feature('extrusion_cbhe_structure11').label('Extrusion for CBHE Structure Work Plane 11');
model.component('component').geom('geometry').feature('extrusion_cbhe_structure11').setIndex('distance', '300', 0);
model.component('component').geom('geometry').feature('extrusion_cbhe_structure11').selection('input').set({'work_plane_cbhe_structure11'});
model.component('component').geom('geometry').create('work_plane_upper_cylinder11', 'WorkPlane');
model.component('component').geom('geometry').feature('work_plane_upper_cylinder11').label('Work Plane for Upper Cylinder 11');
model.component('component').geom('geometry').feature('work_plane_upper_cylinder11').set('planetype', 'normalvector');
model.component('component').geom('geometry').feature('work_plane_upper_cylinder11').set('normalvector', {'0.707107' '0.000000' '-0.707107'});
model.component('component').geom('geometry').feature('work_plane_upper_cylinder11').set('normalcoord', {'20.506097' '60.000000' '-120.506097'});
model.component('component').geom('geometry').feature('work_plane_upper_cylinder11').set('unite', true);
model.component('component').geom('geometry').feature('work_plane_upper_cylinder11').geom.create('circle1', 'Circle');
model.component('component').geom('geometry').create('extrusion_upper_cylinder11', 'Extrude');
model.component('component').geom('geometry').feature('extrusion_upper_cylinder11').label('Extrusion for Upper Cylinder Work Plane 11');
model.component('component').geom('geometry').feature('extrusion_upper_cylinder11').selection('input').set({'work_plane_upper_cylinder11'});
model.component('component').geom('geometry').create('work_plane_lower_cylinder11', 'WorkPlane');
model.component('component').geom('geometry').feature('work_plane_lower_cylinder11').label('Work Plane for Lower Cylinder 11');
model.component('component').geom('geometry').feature('work_plane_lower_cylinder11').set('planetype', 'normalvector');
model.component('component').geom('geometry').feature('work_plane_lower_cylinder11').set('normalvector', {'0.707107' '0.000000' '-0.707107'});
model.component('component').geom('geometry').feature('work_plane_lower_cylinder11').set('normalcoord', {'233.345238' '60.000000' '-333.345238'});
model.component('component').geom('geometry').feature('work_plane_lower_cylinder11').set('unite', true);
model.component('component').geom('geometry').feature('work_plane_lower_cylinder11').geom.create('circle1', 'Circle');
model.component('component').geom('geometry').create('extrusion_lower_cylinder11', 'Extrude');
model.component('component').geom('geometry').feature('extrusion_lower_cylinder11').label('Extrusion for Lower Cylinder Work Plane 11');
model.component('component').geom('geometry').feature('extrusion_lower_cylinder11').selection('input').set({'work_plane_lower_cylinder11'});
model.component('component').geom('geometry').create('work_plane_cbhe_structure12', 'WorkPlane');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure12').label('Work Plane for CBHE Structure 12');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure12').set('planetype', 'normalvector');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure12').set('normalvector', {'1.000000' '0.000000' '0.000000'});
model.component('component').geom('geometry').feature('work_plane_cbhe_structure12').set('normalcoord', {'30.000000' '60.000000' '-100.000000'});
model.component('component').geom('geometry').feature('work_plane_cbhe_structure12').set('unite', true);
model.component('component').geom('geometry').feature('work_plane_cbhe_structure12').geom.create('circle1', 'Circle');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure12').geom.create('circle2', 'Circle');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure12').geom.feature('circle2').set('r', 0.038);
model.component('component').geom('geometry').feature('work_plane_cbhe_structure12').geom.create('circle3', 'Circle');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure12').geom.feature('circle3').set('r', 0.025);
model.component('component').geom('geometry').feature('work_plane_cbhe_structure12').geom.create('circle4', 'Circle');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure12').geom.feature('circle4').set('r', 0.016);
model.component('component').geom('geometry').create('extrusion_cbhe_structure12', 'Extrude');
model.component('component').geom('geometry').feature('extrusion_cbhe_structure12').label('Extrusion for CBHE Structure Work Plane 12');
model.component('component').geom('geometry').feature('extrusion_cbhe_structure12').setIndex('distance', '300', 0);
model.component('component').geom('geometry').feature('extrusion_cbhe_structure12').selection('input').set({'work_plane_cbhe_structure12'});
model.component('component').geom('geometry').create('work_plane_upper_cylinder12', 'WorkPlane');
model.component('component').geom('geometry').feature('work_plane_upper_cylinder12').label('Work Plane for Upper Cylinder 12');
model.component('component').geom('geometry').feature('work_plane_upper_cylinder12').set('planetype', 'normalvector');
model.component('component').geom('geometry').feature('work_plane_upper_cylinder12').set('normalvector', {'1.000000' '0.000000' '0.000000'});
model.component('component').geom('geometry').feature('work_plane_upper_cylinder12').set('normalcoord', {'29.000000' '60.000000' '-100.000000'});
model.component('component').geom('geometry').feature('work_plane_upper_cylinder12').set('unite', true);
model.component('component').geom('geometry').feature('work_plane_upper_cylinder12').geom.create('circle1', 'Circle');
model.component('component').geom('geometry').create('extrusion_upper_cylinder12', 'Extrude');
model.component('component').geom('geometry').feature('extrusion_upper_cylinder12').label('Extrusion for Upper Cylinder Work Plane 12');
model.component('component').geom('geometry').feature('extrusion_upper_cylinder12').selection('input').set({'work_plane_upper_cylinder12'});
model.component('component').geom('geometry').create('work_plane_lower_cylinder12', 'WorkPlane');
model.component('component').geom('geometry').feature('work_plane_lower_cylinder12').label('Work Plane for Lower Cylinder 12');
model.component('component').geom('geometry').feature('work_plane_lower_cylinder12').set('planetype', 'normalvector');
model.component('component').geom('geometry').feature('work_plane_lower_cylinder12').set('normalvector', {'1.000000' '0.000000' '0.000000'});
model.component('component').geom('geometry').feature('work_plane_lower_cylinder12').set('normalcoord', {'330.000000' '60.000000' '-100.000000'});
model.component('component').geom('geometry').feature('work_plane_lower_cylinder12').set('unite', true);
model.component('component').geom('geometry').feature('work_plane_lower_cylinder12').geom.create('circle1', 'Circle');
model.component('component').geom('geometry').create('extrusion_lower_cylinder12', 'Extrude');
model.component('component').geom('geometry').feature('extrusion_lower_cylinder12').label('Extrusion for Lower Cylinder Work Plane 12');
model.component('component').geom('geometry').feature('extrusion_lower_cylinder12').selection('input').set({'work_plane_lower_cylinder12'});
model.component('component').geom('geometry').create('work_plane_cbhe_structure13', 'WorkPlane');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure13').label('Work Plane for CBHE Structure 13');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure13').set('planetype', 'normalvector');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure13').set('normalvector', {'0.173648' '0.000000' '-0.984808'});
model.component('component').geom('geometry').feature('work_plane_cbhe_structure13').set('normalcoord', {'5.209445' '80.000000' '-129.544233'});
model.component('component').geom('geometry').feature('work_plane_cbhe_structure13').set('unite', true);
model.component('component').geom('geometry').feature('work_plane_cbhe_structure13').geom.create('circle1', 'Circle');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure13').geom.create('circle2', 'Circle');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure13').geom.feature('circle2').set('r', 0.038);
model.component('component').geom('geometry').feature('work_plane_cbhe_structure13').geom.create('circle3', 'Circle');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure13').geom.feature('circle3').set('r', 0.025);
model.component('component').geom('geometry').feature('work_plane_cbhe_structure13').geom.create('circle4', 'Circle');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure13').geom.feature('circle4').set('r', 0.016);
model.component('component').geom('geometry').create('extrusion_cbhe_structure13', 'Extrude');
model.component('component').geom('geometry').feature('extrusion_cbhe_structure13').label('Extrusion for CBHE Structure Work Plane 13');
model.component('component').geom('geometry').feature('extrusion_cbhe_structure13').setIndex('distance', '300', 0);
model.component('component').geom('geometry').feature('extrusion_cbhe_structure13').selection('input').set({'work_plane_cbhe_structure13'});
model.component('component').geom('geometry').create('work_plane_upper_cylinder13', 'WorkPlane');
model.component('component').geom('geometry').feature('work_plane_upper_cylinder13').label('Work Plane for Upper Cylinder 13');
model.component('component').geom('geometry').feature('work_plane_upper_cylinder13').set('planetype', 'normalvector');
model.component('component').geom('geometry').feature('work_plane_upper_cylinder13').set('normalvector', {'0.173648' '0.000000' '-0.984808'});
model.component('component').geom('geometry').feature('work_plane_upper_cylinder13').set('normalcoord', {'5.035797' '80.000000' '-128.559425'});
model.component('component').geom('geometry').feature('work_plane_upper_cylinder13').set('unite', true);
model.component('component').geom('geometry').feature('work_plane_upper_cylinder13').geom.create('circle1', 'Circle');
model.component('component').geom('geometry').create('extrusion_upper_cylinder13', 'Extrude');
model.component('component').geom('geometry').feature('extrusion_upper_cylinder13').label('Extrusion for Upper Cylinder Work Plane 13');
model.component('component').geom('geometry').feature('extrusion_upper_cylinder13').selection('input').set({'work_plane_upper_cylinder13'});
model.component('component').geom('geometry').create('work_plane_lower_cylinder13', 'WorkPlane');
model.component('component').geom('geometry').feature('work_plane_lower_cylinder13').label('Work Plane for Lower Cylinder 13');
model.component('component').geom('geometry').feature('work_plane_lower_cylinder13').set('planetype', 'normalvector');
model.component('component').geom('geometry').feature('work_plane_lower_cylinder13').set('normalvector', {'0.173648' '0.000000' '-0.984808'});
model.component('component').geom('geometry').feature('work_plane_lower_cylinder13').set('normalcoord', {'57.303899' '80.000000' '-424.986558'});
model.component('component').geom('geometry').feature('work_plane_lower_cylinder13').set('unite', true);
model.component('component').geom('geometry').feature('work_plane_lower_cylinder13').geom.create('circle1', 'Circle');
model.component('component').geom('geometry').create('extrusion_lower_cylinder13', 'Extrude');
model.component('component').geom('geometry').feature('extrusion_lower_cylinder13').label('Extrusion for Lower Cylinder Work Plane 13');
model.component('component').geom('geometry').feature('extrusion_lower_cylinder13').selection('input').set({'work_plane_lower_cylinder13'});
model.component('component').geom('geometry').create('work_plane_cbhe_structure14', 'WorkPlane');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure14').label('Work Plane for CBHE Structure 14');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure14').set('planetype', 'normalvector');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure14').set('normalvector', {'0.707107' '0.000000' '-0.707107'});
model.component('component').geom('geometry').feature('work_plane_cbhe_structure14').set('normalcoord', {'21.213203' '80.000000' '-121.213203'});
model.component('component').geom('geometry').feature('work_plane_cbhe_structure14').set('unite', true);
model.component('component').geom('geometry').feature('work_plane_cbhe_structure14').geom.create('circle1', 'Circle');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure14').geom.create('circle2', 'Circle');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure14').geom.feature('circle2').set('r', 0.038);
model.component('component').geom('geometry').feature('work_plane_cbhe_structure14').geom.create('circle3', 'Circle');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure14').geom.feature('circle3').set('r', 0.025);
model.component('component').geom('geometry').feature('work_plane_cbhe_structure14').geom.create('circle4', 'Circle');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure14').geom.feature('circle4').set('r', 0.016);
model.component('component').geom('geometry').create('extrusion_cbhe_structure14', 'Extrude');
model.component('component').geom('geometry').feature('extrusion_cbhe_structure14').label('Extrusion for CBHE Structure Work Plane 14');
model.component('component').geom('geometry').feature('extrusion_cbhe_structure14').setIndex('distance', '300', 0);
model.component('component').geom('geometry').feature('extrusion_cbhe_structure14').selection('input').set({'work_plane_cbhe_structure14'});
model.component('component').geom('geometry').create('work_plane_upper_cylinder14', 'WorkPlane');
model.component('component').geom('geometry').feature('work_plane_upper_cylinder14').label('Work Plane for Upper Cylinder 14');
model.component('component').geom('geometry').feature('work_plane_upper_cylinder14').set('planetype', 'normalvector');
model.component('component').geom('geometry').feature('work_plane_upper_cylinder14').set('normalvector', {'0.707107' '0.000000' '-0.707107'});
model.component('component').geom('geometry').feature('work_plane_upper_cylinder14').set('normalcoord', {'20.506097' '80.000000' '-120.506097'});
model.component('component').geom('geometry').feature('work_plane_upper_cylinder14').set('unite', true);
model.component('component').geom('geometry').feature('work_plane_upper_cylinder14').geom.create('circle1', 'Circle');
model.component('component').geom('geometry').create('extrusion_upper_cylinder14', 'Extrude');
model.component('component').geom('geometry').feature('extrusion_upper_cylinder14').label('Extrusion for Upper Cylinder Work Plane 14');
model.component('component').geom('geometry').feature('extrusion_upper_cylinder14').selection('input').set({'work_plane_upper_cylinder14'});
model.component('component').geom('geometry').create('work_plane_lower_cylinder14', 'WorkPlane');
model.component('component').geom('geometry').feature('work_plane_lower_cylinder14').label('Work Plane for Lower Cylinder 14');
model.component('component').geom('geometry').feature('work_plane_lower_cylinder14').set('planetype', 'normalvector');
model.component('component').geom('geometry').feature('work_plane_lower_cylinder14').set('normalvector', {'0.707107' '0.000000' '-0.707107'});
model.component('component').geom('geometry').feature('work_plane_lower_cylinder14').set('normalcoord', {'233.345238' '80.000000' '-333.345238'});
model.component('component').geom('geometry').feature('work_plane_lower_cylinder14').set('unite', true);
model.component('component').geom('geometry').feature('work_plane_lower_cylinder14').geom.create('circle1', 'Circle');
model.component('component').geom('geometry').create('extrusion_lower_cylinder14', 'Extrude');
model.component('component').geom('geometry').feature('extrusion_lower_cylinder14').label('Extrusion for Lower Cylinder Work Plane 14');
model.component('component').geom('geometry').feature('extrusion_lower_cylinder14').selection('input').set({'work_plane_lower_cylinder14'});
model.component('component').geom('geometry').create('work_plane_cbhe_structure15', 'WorkPlane');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure15').label('Work Plane for CBHE Structure 15');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure15').set('planetype', 'normalvector');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure15').set('normalvector', {'1.000000' '0.000000' '0.000000'});
model.component('component').geom('geometry').feature('work_plane_cbhe_structure15').set('normalcoord', {'30.000000' '80.000000' '-100.000000'});
model.component('component').geom('geometry').feature('work_plane_cbhe_structure15').set('unite', true);
model.component('component').geom('geometry').feature('work_plane_cbhe_structure15').geom.create('circle1', 'Circle');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure15').geom.create('circle2', 'Circle');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure15').geom.feature('circle2').set('r', 0.038);
model.component('component').geom('geometry').feature('work_plane_cbhe_structure15').geom.create('circle3', 'Circle');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure15').geom.feature('circle3').set('r', 0.025);
model.component('component').geom('geometry').feature('work_plane_cbhe_structure15').geom.create('circle4', 'Circle');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure15').geom.feature('circle4').set('r', 0.016);
model.component('component').geom('geometry').create('extrusion_cbhe_structure15', 'Extrude');
model.component('component').geom('geometry').feature('extrusion_cbhe_structure15').label('Extrusion for CBHE Structure Work Plane 15');
model.component('component').geom('geometry').feature('extrusion_cbhe_structure15').setIndex('distance', '300', 0);
model.component('component').geom('geometry').feature('extrusion_cbhe_structure15').selection('input').set({'work_plane_cbhe_structure15'});
model.component('component').geom('geometry').create('work_plane_upper_cylinder15', 'WorkPlane');
model.component('component').geom('geometry').feature('work_plane_upper_cylinder15').label('Work Plane for Upper Cylinder 15');
model.component('component').geom('geometry').feature('work_plane_upper_cylinder15').set('planetype', 'normalvector');
model.component('component').geom('geometry').feature('work_plane_upper_cylinder15').set('normalvector', {'1.000000' '0.000000' '0.000000'});
model.component('component').geom('geometry').feature('work_plane_upper_cylinder15').set('normalcoord', {'29.000000' '80.000000' '-100.000000'});
model.component('component').geom('geometry').feature('work_plane_upper_cylinder15').set('unite', true);
model.component('component').geom('geometry').feature('work_plane_upper_cylinder15').geom.create('circle1', 'Circle');
model.component('component').geom('geometry').create('extrusion_upper_cylinder15', 'Extrude');
model.component('component').geom('geometry').feature('extrusion_upper_cylinder15').label('Extrusion for Upper Cylinder Work Plane 15');
model.component('component').geom('geometry').feature('extrusion_upper_cylinder15').selection('input').set({'work_plane_upper_cylinder15'});
model.component('component').geom('geometry').create('work_plane_lower_cylinder15', 'WorkPlane');
model.component('component').geom('geometry').feature('work_plane_lower_cylinder15').label('Work Plane for Lower Cylinder 15');
model.component('component').geom('geometry').feature('work_plane_lower_cylinder15').set('planetype', 'normalvector');
model.component('component').geom('geometry').feature('work_plane_lower_cylinder15').set('normalvector', {'1.000000' '0.000000' '0.000000'});
model.component('component').geom('geometry').feature('work_plane_lower_cylinder15').set('normalcoord', {'330.000000' '80.000000' '-100.000000'});
model.component('component').geom('geometry').feature('work_plane_lower_cylinder15').set('unite', true);
model.component('component').geom('geometry').feature('work_plane_lower_cylinder15').geom.create('circle1', 'Circle');
model.component('component').geom('geometry').create('extrusion_lower_cylinder15', 'Extrude');
model.component('component').geom('geometry').feature('extrusion_lower_cylinder15').label('Extrusion for Lower Cylinder Work Plane 15');
model.component('component').geom('geometry').feature('extrusion_lower_cylinder15').selection('input').set({'work_plane_lower_cylinder15'});
model.component('component').geom('geometry').create('work_plane_cbhe_structure16', 'WorkPlane');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure16').label('Work Plane for CBHE Structure 16');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure16').set('planetype', 'normalvector');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure16').set('normalvector', {'0.173648' '0.000000' '-0.984808'});
model.component('component').geom('geometry').feature('work_plane_cbhe_structure16').set('normalcoord', {'5.209445' '100.000000' '-129.544233'});
model.component('component').geom('geometry').feature('work_plane_cbhe_structure16').set('unite', true);
model.component('component').geom('geometry').feature('work_plane_cbhe_structure16').geom.create('circle1', 'Circle');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure16').geom.create('circle2', 'Circle');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure16').geom.feature('circle2').set('r', 0.038);
model.component('component').geom('geometry').feature('work_plane_cbhe_structure16').geom.create('circle3', 'Circle');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure16').geom.feature('circle3').set('r', 0.025);
model.component('component').geom('geometry').feature('work_plane_cbhe_structure16').geom.create('circle4', 'Circle');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure16').geom.feature('circle4').set('r', 0.016);
model.component('component').geom('geometry').create('extrusion_cbhe_structure16', 'Extrude');
model.component('component').geom('geometry').feature('extrusion_cbhe_structure16').label('Extrusion for CBHE Structure Work Plane 16');
model.component('component').geom('geometry').feature('extrusion_cbhe_structure16').setIndex('distance', '300', 0);
model.component('component').geom('geometry').feature('extrusion_cbhe_structure16').selection('input').set({'work_plane_cbhe_structure16'});
model.component('component').geom('geometry').create('work_plane_upper_cylinder16', 'WorkPlane');
model.component('component').geom('geometry').feature('work_plane_upper_cylinder16').label('Work Plane for Upper Cylinder 16');
model.component('component').geom('geometry').feature('work_plane_upper_cylinder16').set('planetype', 'normalvector');
model.component('component').geom('geometry').feature('work_plane_upper_cylinder16').set('normalvector', {'0.173648' '0.000000' '-0.984808'});
model.component('component').geom('geometry').feature('work_plane_upper_cylinder16').set('normalcoord', {'5.035797' '100.000000' '-128.559425'});
model.component('component').geom('geometry').feature('work_plane_upper_cylinder16').set('unite', true);
model.component('component').geom('geometry').feature('work_plane_upper_cylinder16').geom.create('circle1', 'Circle');
model.component('component').geom('geometry').create('extrusion_upper_cylinder16', 'Extrude');
model.component('component').geom('geometry').feature('extrusion_upper_cylinder16').label('Extrusion for Upper Cylinder Work Plane 16');
model.component('component').geom('geometry').feature('extrusion_upper_cylinder16').selection('input').set({'work_plane_upper_cylinder16'});
model.component('component').geom('geometry').create('work_plane_lower_cylinder16', 'WorkPlane');
model.component('component').geom('geometry').feature('work_plane_lower_cylinder16').label('Work Plane for Lower Cylinder 16');
model.component('component').geom('geometry').feature('work_plane_lower_cylinder16').set('planetype', 'normalvector');
model.component('component').geom('geometry').feature('work_plane_lower_cylinder16').set('normalvector', {'0.173648' '0.000000' '-0.984808'});
model.component('component').geom('geometry').feature('work_plane_lower_cylinder16').set('normalcoord', {'57.303899' '100.000000' '-424.986558'});
model.component('component').geom('geometry').feature('work_plane_lower_cylinder16').set('unite', true);
model.component('component').geom('geometry').feature('work_plane_lower_cylinder16').geom.create('circle1', 'Circle');
model.component('component').geom('geometry').create('extrusion_lower_cylinder16', 'Extrude');
model.component('component').geom('geometry').feature('extrusion_lower_cylinder16').label('Extrusion for Lower Cylinder Work Plane 16');
model.component('component').geom('geometry').feature('extrusion_lower_cylinder16').selection('input').set({'work_plane_lower_cylinder16'});
model.component('component').geom('geometry').create('work_plane_cbhe_structure17', 'WorkPlane');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure17').label('Work Plane for CBHE Structure 17');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure17').set('planetype', 'normalvector');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure17').set('normalvector', {'0.707107' '0.000000' '-0.707107'});
model.component('component').geom('geometry').feature('work_plane_cbhe_structure17').set('normalcoord', {'21.213203' '100.000000' '-121.213203'});
model.component('component').geom('geometry').feature('work_plane_cbhe_structure17').set('unite', true);
model.component('component').geom('geometry').feature('work_plane_cbhe_structure17').geom.create('circle1', 'Circle');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure17').geom.create('circle2', 'Circle');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure17').geom.feature('circle2').set('r', 0.038);
model.component('component').geom('geometry').feature('work_plane_cbhe_structure17').geom.create('circle3', 'Circle');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure17').geom.feature('circle3').set('r', 0.025);
model.component('component').geom('geometry').feature('work_plane_cbhe_structure17').geom.create('circle4', 'Circle');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure17').geom.feature('circle4').set('r', 0.016);
model.component('component').geom('geometry').create('extrusion_cbhe_structure17', 'Extrude');
model.component('component').geom('geometry').feature('extrusion_cbhe_structure17').label('Extrusion for CBHE Structure Work Plane 17');
model.component('component').geom('geometry').feature('extrusion_cbhe_structure17').setIndex('distance', '300', 0);
model.component('component').geom('geometry').feature('extrusion_cbhe_structure17').selection('input').set({'work_plane_cbhe_structure17'});
model.component('component').geom('geometry').create('work_plane_upper_cylinder17', 'WorkPlane');
model.component('component').geom('geometry').feature('work_plane_upper_cylinder17').label('Work Plane for Upper Cylinder 17');
model.component('component').geom('geometry').feature('work_plane_upper_cylinder17').set('planetype', 'normalvector');
model.component('component').geom('geometry').feature('work_plane_upper_cylinder17').set('normalvector', {'0.707107' '0.000000' '-0.707107'});
model.component('component').geom('geometry').feature('work_plane_upper_cylinder17').set('normalcoord', {'20.506097' '100.000000' '-120.506097'});
model.component('component').geom('geometry').feature('work_plane_upper_cylinder17').set('unite', true);
model.component('component').geom('geometry').feature('work_plane_upper_cylinder17').geom.create('circle1', 'Circle');
model.component('component').geom('geometry').create('extrusion_upper_cylinder17', 'Extrude');
model.component('component').geom('geometry').feature('extrusion_upper_cylinder17').label('Extrusion for Upper Cylinder Work Plane 17');
model.component('component').geom('geometry').feature('extrusion_upper_cylinder17').selection('input').set({'work_plane_upper_cylinder17'});
model.component('component').geom('geometry').create('work_plane_lower_cylinder17', 'WorkPlane');
model.component('component').geom('geometry').feature('work_plane_lower_cylinder17').label('Work Plane for Lower Cylinder 17');
model.component('component').geom('geometry').feature('work_plane_lower_cylinder17').set('planetype', 'normalvector');
model.component('component').geom('geometry').feature('work_plane_lower_cylinder17').set('normalvector', {'0.707107' '0.000000' '-0.707107'});
model.component('component').geom('geometry').feature('work_plane_lower_cylinder17').set('normalcoord', {'233.345238' '100.000000' '-333.345238'});
model.component('component').geom('geometry').feature('work_plane_lower_cylinder17').set('unite', true);
model.component('component').geom('geometry').feature('work_plane_lower_cylinder17').geom.create('circle1', 'Circle');
model.component('component').geom('geometry').create('extrusion_lower_cylinder17', 'Extrude');
model.component('component').geom('geometry').feature('extrusion_lower_cylinder17').label('Extrusion for Lower Cylinder Work Plane 17');
model.component('component').geom('geometry').feature('extrusion_lower_cylinder17').selection('input').set({'work_plane_lower_cylinder17'});
model.component('component').geom('geometry').create('work_plane_cbhe_structure18', 'WorkPlane');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure18').label('Work Plane for CBHE Structure 18');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure18').set('planetype', 'normalvector');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure18').set('normalvector', {'1.000000' '0.000000' '0.000000'});
model.component('component').geom('geometry').feature('work_plane_cbhe_structure18').set('normalcoord', {'30.000000' '100.000000' '-100.000000'});
model.component('component').geom('geometry').feature('work_plane_cbhe_structure18').set('unite', true);
model.component('component').geom('geometry').feature('work_plane_cbhe_structure18').geom.create('circle1', 'Circle');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure18').geom.create('circle2', 'Circle');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure18').geom.feature('circle2').set('r', 0.038);
model.component('component').geom('geometry').feature('work_plane_cbhe_structure18').geom.create('circle3', 'Circle');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure18').geom.feature('circle3').set('r', 0.025);
model.component('component').geom('geometry').feature('work_plane_cbhe_structure18').geom.create('circle4', 'Circle');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure18').geom.feature('circle4').set('r', 0.016);
model.component('component').geom('geometry').create('extrusion_cbhe_structure18', 'Extrude');
model.component('component').geom('geometry').feature('extrusion_cbhe_structure18').label('Extrusion for CBHE Structure Work Plane 18');
model.component('component').geom('geometry').feature('extrusion_cbhe_structure18').setIndex('distance', '300', 0);
model.component('component').geom('geometry').feature('extrusion_cbhe_structure18').selection('input').set({'work_plane_cbhe_structure18'});
model.component('component').geom('geometry').create('work_plane_upper_cylinder18', 'WorkPlane');
model.component('component').geom('geometry').feature('work_plane_upper_cylinder18').label('Work Plane for Upper Cylinder 18');
model.component('component').geom('geometry').feature('work_plane_upper_cylinder18').set('planetype', 'normalvector');
model.component('component').geom('geometry').feature('work_plane_upper_cylinder18').set('normalvector', {'1.000000' '0.000000' '0.000000'});
model.component('component').geom('geometry').feature('work_plane_upper_cylinder18').set('normalcoord', {'29.000000' '100.000000' '-100.000000'});
model.component('component').geom('geometry').feature('work_plane_upper_cylinder18').set('unite', true);
model.component('component').geom('geometry').feature('work_plane_upper_cylinder18').geom.create('circle1', 'Circle');
model.component('component').geom('geometry').create('extrusion_upper_cylinder18', 'Extrude');
model.component('component').geom('geometry').feature('extrusion_upper_cylinder18').label('Extrusion for Upper Cylinder Work Plane 18');
model.component('component').geom('geometry').feature('extrusion_upper_cylinder18').selection('input').set({'work_plane_upper_cylinder18'});
model.component('component').geom('geometry').create('work_plane_lower_cylinder18', 'WorkPlane');
model.component('component').geom('geometry').feature('work_plane_lower_cylinder18').label('Work Plane for Lower Cylinder 18');
model.component('component').geom('geometry').feature('work_plane_lower_cylinder18').set('planetype', 'normalvector');
model.component('component').geom('geometry').feature('work_plane_lower_cylinder18').set('normalvector', {'1.000000' '0.000000' '0.000000'});
model.component('component').geom('geometry').feature('work_plane_lower_cylinder18').set('normalcoord', {'330.000000' '100.000000' '-100.000000'});
model.component('component').geom('geometry').feature('work_plane_lower_cylinder18').set('unite', true);
model.component('component').geom('geometry').feature('work_plane_lower_cylinder18').geom.create('circle1', 'Circle');
model.component('component').geom('geometry').create('extrusion_lower_cylinder18', 'Extrude');
model.component('component').geom('geometry').feature('extrusion_lower_cylinder18').label('Extrusion for Lower Cylinder Work Plane 18');
model.component('component').geom('geometry').feature('extrusion_lower_cylinder18').selection('input').set({'work_plane_lower_cylinder18'});
model.component('component').geom('geometry').create('bedrock_block', 'Block');
model.component('component').geom('geometry').feature('bedrock_block').set('pos', [0 0 -630]);
model.component('component').geom('geometry').feature('bedrock_block').set('size', [630 410 630]);
model.component('component').geom('geometry').run('fin');
model.component('component').geom('geometry').create('boxsel1', 'BoxSelection');
model.component('component').geom('geometry').feature('boxsel1').set('entitydim', 2);
model.component('component').geom('geometry').feature('boxsel1').set('xmin', '-1[mm]');
model.component('component').geom('geometry').feature('boxsel1').set('xmax', '700+1[mm]');
model.component('component').geom('geometry').feature('boxsel1').set('ymin', '-1[mm]');
model.component('component').geom('geometry').feature('boxsel1').set('ymax', '700+1[mm]');
model.component('component').geom('geometry').feature('boxsel1').set('zmin', '-1[mm]');
model.component('component').geom('geometry').feature('boxsel1').set('zmax', '+1[mm]');
model.component('component').geom('geometry').feature('boxsel1').set('condition', 'allvertices');
model.component('component').geom('geometry').run;

model.component('component').view('view1').set('renderwireframe', true);

out = model;
