function out = model
%
% temp.m
%
% Model exported on Jan 29 2020, 17:34 by COMSOL 5.5.0.292.

import com.comsol.model.*
import com.comsol.model.util.*

model = ModelUtil.create('Model');

model.modelPath('E:\Work\Energiakaivos\Code');

model.label('temp.mph');

model.param.set('q_geothermal', '40[mW/m^2]');
model.param.set('T_surface', '2.3[degC]');
model.param.set('T_inlet', '6[degC]');
model.param.set('k_rock', '3[W/(m*K)]');
model.param.set('Cp_rock', '750[J/(kg*K)]');
model.param.set('rho_rock', '2700[kg/m^3]');

model.component.create('component', true);

model.component('component').geom.create('geometry', 3);

model.func.create('initial_temperature_function', 'Analytic');
model.func('initial_temperature_function').label('Initial Temperature Function');
model.func('initial_temperature_function').set('funcname', 'T_initial');
model.func('initial_temperature_function').set('expr', 'T_surface-q_geothermal/k_rock*z');
model.func('initial_temperature_function').set('args', {'z'});
model.func('initial_temperature_function').set('argunit', 'm');
model.func('initial_temperature_function').set('fununit', 'K');
model.func('initial_temperature_function').set('plotargs', {'z' '0' '1'});

model.component('component').mesh.create('mesh');

model.component('component').geom('geometry').create('work_plane_cbhe_structure1', 'WorkPlane');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure1').label('Work Plane for CBHE Structure 1');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure1').set('planetype', 'normalvector');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure1').set('normalvector', {'0.500000' '0.500000' '-0.707107'});
model.component('component').geom('geometry').feature('work_plane_cbhe_structure1').set('normalcoord', {'10.000000' '10.000000' '-14.142136'});
model.component('component').geom('geometry').feature('work_plane_cbhe_structure1').set('unite', true);
model.component('component').geom('geometry').feature('work_plane_cbhe_structure1').geom.create('circle1', 'Circle');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure1').geom.feature('circle1').set('r', 0.5);
model.component('component').geom('geometry').feature('work_plane_cbhe_structure1').geom.create('circle2', 'Circle');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure1').geom.feature('circle2').set('r', 0.038);
model.component('component').geom('geometry').feature('work_plane_cbhe_structure1').geom.create('circle3', 'Circle');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure1').geom.feature('circle3').set('r', 0.025);
model.component('component').geom('geometry').feature('work_plane_cbhe_structure1').geom.create('circle4', 'Circle');
model.component('component').geom('geometry').feature('work_plane_cbhe_structure1').geom.feature('circle4').set('r', 0.016);
model.component('component').geom('geometry').create('extrusion_cbhe_structure1', 'Extrude');
model.component('component').geom('geometry').feature('extrusion_cbhe_structure1').label('Extrusion for CBHE Structure Work Plane 1');
model.component('component').geom('geometry').feature('extrusion_cbhe_structure1').setIndex('distance', '300', 0);
model.component('component').geom('geometry').feature('extrusion_cbhe_structure1').selection('input').set({'work_plane_cbhe_structure1'});
model.component('component').geom('geometry').create('work_plane_upper_cylinder1', 'WorkPlane');
model.component('component').geom('geometry').feature('work_plane_upper_cylinder1').label('Work Plane for Upper Cylinder 1');
model.component('component').geom('geometry').feature('work_plane_upper_cylinder1').set('planetype', 'normalvector');
model.component('component').geom('geometry').feature('work_plane_upper_cylinder1').set('normalvector', {'0.500000' '0.500000' '-0.707107'});
model.component('component').geom('geometry').feature('work_plane_upper_cylinder1').set('normalcoord', {'9.750000' '9.750000' '-13.788582'});
model.component('component').geom('geometry').feature('work_plane_upper_cylinder1').set('unite', true);
model.component('component').geom('geometry').feature('work_plane_upper_cylinder1').geom.create('circle1', 'Circle');
model.component('component').geom('geometry').feature('work_plane_upper_cylinder1').geom.feature('circle1').set('r', 0.5);
model.component('component').geom('geometry').create('extrusion_upper_cylinder1', 'Extrude');
model.component('component').geom('geometry').feature('extrusion_upper_cylinder1').label('Extrusion for Upper Cylinder Work Plane 1');
model.component('component').geom('geometry').feature('extrusion_upper_cylinder1').setIndex('distance', '0.5', 0);
model.component('component').geom('geometry').feature('extrusion_upper_cylinder1').selection('input').set({'work_plane_upper_cylinder1'});
model.component('component').geom('geometry').create('work_plane_lower_cylinder1', 'WorkPlane');
model.component('component').geom('geometry').feature('work_plane_lower_cylinder1').label('Work Plane for Lower Cylinder 1');
model.component('component').geom('geometry').feature('work_plane_lower_cylinder1').set('planetype', 'normalvector');
model.component('component').geom('geometry').feature('work_plane_lower_cylinder1').set('normalvector', {'0.500000' '0.500000' '-0.707107'});
model.component('component').geom('geometry').feature('work_plane_lower_cylinder1').set('normalcoord', {'160.000000' '160.000000' '-226.274170'});
model.component('component').geom('geometry').feature('work_plane_lower_cylinder1').set('unite', true);
model.component('component').geom('geometry').feature('work_plane_lower_cylinder1').geom.create('circle1', 'Circle');
model.component('component').geom('geometry').feature('work_plane_lower_cylinder1').geom.feature('circle1').set('r', 0.5);
model.component('component').geom('geometry').create('extrusion_lower_cylinder1', 'Extrude');
model.component('component').geom('geometry').feature('extrusion_lower_cylinder1').label('Extrusion for Lower Cylinder Work Plane 1');
model.component('component').geom('geometry').feature('extrusion_lower_cylinder1').setIndex('distance', '0.5', 0);
model.component('component').geom('geometry').feature('extrusion_lower_cylinder1').selection('input').set({'work_plane_lower_cylinder1'});
model.component('component').geom('geometry').run('fin');
model.component('component').geom('geometry').create('buffer_zone_selection1', 'CylinderSelection');
model.component('component').geom('geometry').feature('buffer_zone_selection1').label('Buffer Zone Selection 1');
model.component('component').geom('geometry').feature('buffer_zone_selection1').set('r', 0.501);
model.component('component').geom('geometry').feature('buffer_zone_selection1').set('rin', 0.037);
model.component('component').geom('geometry').feature('buffer_zone_selection1').set('top', 300.001);
model.component('component').geom('geometry').feature('buffer_zone_selection1').set('bottom', -0.001);
model.component('component').geom('geometry').feature('buffer_zone_selection1').set('pos', {'10.000000' '10.000000' '-14.142136'});
model.component('component').geom('geometry').feature('buffer_zone_selection1').set('axis', {'0.500000' '0.500000' '-0.707107'});
model.component('component').geom('geometry').feature('buffer_zone_selection1').set('condition', 'allvertices');
model.component('component').geom('geometry').create('outer_fluid_selection1', 'CylinderSelection');
model.component('component').geom('geometry').feature('outer_fluid_selection1').label('Outer Fluid Selection 1');
model.component('component').geom('geometry').feature('outer_fluid_selection1').set('r', 0.039);
model.component('component').geom('geometry').feature('outer_fluid_selection1').set('rin', 0.024);
model.component('component').geom('geometry').feature('outer_fluid_selection1').set('top', 300.001);
model.component('component').geom('geometry').feature('outer_fluid_selection1').set('bottom', -0.001);
model.component('component').geom('geometry').feature('outer_fluid_selection1').set('pos', {'10.000000' '10.000000' '-14.142136'});
model.component('component').geom('geometry').feature('outer_fluid_selection1').set('axis', {'0.500000' '0.500000' '-0.707107'});
model.component('component').geom('geometry').feature('outer_fluid_selection1').set('condition', 'allvertices');
model.component('component').geom('geometry').create('pipe_wall_selection1', 'CylinderSelection');
model.component('component').geom('geometry').feature('pipe_wall_selection1').label('Pipe Wall Selection 1');
model.component('component').geom('geometry').feature('pipe_wall_selection1').set('r', 0.026000000000000002);
model.component('component').geom('geometry').feature('pipe_wall_selection1').set('rin', 0.001);
model.component('component').geom('geometry').feature('pipe_wall_selection1').set('top', 300.001);
model.component('component').geom('geometry').feature('pipe_wall_selection1').set('bottom', -0.001);
model.component('component').geom('geometry').feature('pipe_wall_selection1').set('pos', {'10.000000' '10.000000' '-14.142136'});
model.component('component').geom('geometry').feature('pipe_wall_selection1').set('axis', {'0.500000' '0.500000' '-0.707107'});
model.component('component').geom('geometry').feature('pipe_wall_selection1').set('condition', 'inside');
model.component('component').geom('geometry').create('inner_fluid_selection1', 'CylinderSelection');
model.component('component').geom('geometry').feature('inner_fluid_selection1').label('Inner Fluid Selection 1');
model.component('component').geom('geometry').feature('inner_fluid_selection1').set('r', 0.017);
model.component('component').geom('geometry').feature('inner_fluid_selection1').set('top', 300.001);
model.component('component').geom('geometry').feature('inner_fluid_selection1').set('bottom', -0.001);
model.component('component').geom('geometry').feature('inner_fluid_selection1').set('pos', {'10.000000' '10.000000' '-14.142136'});
model.component('component').geom('geometry').feature('inner_fluid_selection1').set('axis', {'0.500000' '0.500000' '-0.707107'});
model.component('component').geom('geometry').feature('inner_fluid_selection1').set('condition', 'allvertices');
model.component('component').geom('geometry').create('borehole_structure_selection1', 'UnionSelection');
model.component('component').geom('geometry').feature('borehole_structure_selection1').set('input', {'buffer_zone_selection1' 'outer_fluid_selection1' 'pipe_wall_selection1' 'inner_fluid_selection1'});
model.component('component').geom('geometry').create('borehole_wall_selection1', 'CylinderSelection');
model.component('component').geom('geometry').feature('borehole_wall_selection1').set('entitydim', 2);
model.component('component').geom('geometry').feature('borehole_wall_selection1').label('Borehole Wall Selection 1');
model.component('component').geom('geometry').feature('borehole_wall_selection1').set('r', 0.039);
model.component('component').geom('geometry').feature('borehole_wall_selection1').set('rin', 0.037);
model.component('component').geom('geometry').feature('borehole_wall_selection1').set('top', 300.001);
model.component('component').geom('geometry').feature('borehole_wall_selection1').set('bottom', -0.001);
model.component('component').geom('geometry').feature('borehole_wall_selection1').set('pos', {'10.000000' '10.000000' '-14.142136'});
model.component('component').geom('geometry').feature('borehole_wall_selection1').set('axis', {'0.500000' '0.500000' '-0.707107'});
model.component('component').geom('geometry').feature('borehole_wall_selection1').set('condition', 'allvertices');
model.component('component').geom('geometry').create('upper_cylinder_selection1', 'CylinderSelection');
model.component('component').geom('geometry').feature('upper_cylinder_selection1').label('Upper Cylinder Selection 1');
model.component('component').geom('geometry').feature('upper_cylinder_selection1').set('r', 0.501);
model.component('component').geom('geometry').feature('upper_cylinder_selection1').set('top', 0.501);
model.component('component').geom('geometry').feature('upper_cylinder_selection1').set('bottom', -0.001);
model.component('component').geom('geometry').feature('upper_cylinder_selection1').set('pos', {'9.750000' '9.750000' '-13.788582'});
model.component('component').geom('geometry').feature('upper_cylinder_selection1').set('axis', {'0.500000' '0.500000' '-0.707107'});
model.component('component').geom('geometry').feature('upper_cylinder_selection1').set('condition', 'allvertices');
model.component('component').geom('geometry').create('lower_cylinder_selection1', 'CylinderSelection');
model.component('component').geom('geometry').feature('lower_cylinder_selection1').label('Lower Cylinder Selection 1');
model.component('component').geom('geometry').feature('lower_cylinder_selection1').set('r', 0.501);
model.component('component').geom('geometry').feature('lower_cylinder_selection1').set('top', 0.501);
model.component('component').geom('geometry').feature('lower_cylinder_selection1').set('bottom', -0.001);
model.component('component').geom('geometry').feature('lower_cylinder_selection1').set('pos', {'160.000000' '160.000000' '-226.274170'});
model.component('component').geom('geometry').feature('lower_cylinder_selection1').set('axis', {'0.500000' '0.500000' '-0.707107'});
model.component('component').geom('geometry').feature('lower_cylinder_selection1').set('condition', 'allvertices');
model.component('component').geom('geometry').create('cylinders_selection1', 'UnionSelection');
model.component('component').geom('geometry').feature('cylinders_selection1').set('input', {'upper_cylinder_selection1' 'lower_cylinder_selection1'});
model.component('component').geom('geometry').create('outer_cap_selection1', 'CylinderSelection');
model.component('component').geom('geometry').feature('outer_cap_selection1').set('entitydim', 2);
model.component('component').geom('geometry').feature('outer_cap_selection1').label('Outer Cap Selection 1');
model.component('component').geom('geometry').feature('outer_cap_selection1').set('r', 0.501);
model.component('component').geom('geometry').feature('outer_cap_selection1').set('rin', 0.037);
model.component('component').geom('geometry').feature('outer_cap_selection1').set('top', 0.001);
model.component('component').geom('geometry').feature('outer_cap_selection1').set('bottom', -0.001);
model.component('component').geom('geometry').feature('outer_cap_selection1').set('pos', {'10.000000' '10.000000' '-14.142136'});
model.component('component').geom('geometry').feature('outer_cap_selection1').set('axis', {'0.500000' '0.500000' '-0.707107'});
model.component('component').geom('geometry').feature('outer_cap_selection1').set('condition', 'inside');
model.component('component').geom('geometry').create('inner_cap_selection1', 'CylinderSelection');
model.component('component').geom('geometry').feature('inner_cap_selection1').set('entitydim', 2);
model.component('component').geom('geometry').feature('inner_cap_selection1').label('Inner Cap Selection 1');
model.component('component').geom('geometry').feature('inner_cap_selection1').set('r', 0.039);
model.component('component').geom('geometry').feature('inner_cap_selection1').set('top', 0.001);
model.component('component').geom('geometry').feature('inner_cap_selection1').set('bottom', -0.001);
model.component('component').geom('geometry').feature('inner_cap_selection1').set('pos', {'10.000000' '10.000000' '-14.142136'});
model.component('component').geom('geometry').feature('inner_cap_selection1').set('axis', {'0.500000' '0.500000' '-0.707107'});
model.component('component').geom('geometry').feature('inner_cap_selection1').set('condition', 'allvertices');
model.component('component').geom('geometry').create('top_inlet_selection1', 'CylinderSelection');
model.component('component').geom('geometry').feature('top_inlet_selection1').set('entitydim', 2);
model.component('component').geom('geometry').feature('top_inlet_selection1').label('Top Inlet Selection 1');
model.component('component').geom('geometry').feature('top_inlet_selection1').set('r', 0.039);
model.component('component').geom('geometry').feature('top_inlet_selection1').set('rin', 0.024);
model.component('component').geom('geometry').feature('top_inlet_selection1').set('top', 0.001);
model.component('component').geom('geometry').feature('top_inlet_selection1').set('bottom', -0.001);
model.component('component').geom('geometry').feature('top_inlet_selection1').set('pos', {'10.000000' '10.000000' '-14.142136'});
model.component('component').geom('geometry').feature('top_inlet_selection1').set('axis', {'0.500000' '0.500000' '-0.707107'});
model.component('component').geom('geometry').feature('top_inlet_selection1').set('condition', 'allvertices');
model.component('component').geom('geometry').create('top_outlet_selection1', 'CylinderSelection');
model.component('component').geom('geometry').feature('top_outlet_selection1').set('entitydim', 2);
model.component('component').geom('geometry').feature('top_outlet_selection1').label('Top Outlet Selection 1');
model.component('component').geom('geometry').feature('top_outlet_selection1').set('r', 0.017);
model.component('component').geom('geometry').feature('top_outlet_selection1').set('top', 0.001);
model.component('component').geom('geometry').feature('top_outlet_selection1').set('bottom', -0.001);
model.component('component').geom('geometry').feature('top_outlet_selection1').set('pos', {'10.000000' '10.000000' '-14.142136'});
model.component('component').geom('geometry').feature('top_outlet_selection1').set('axis', {'0.500000' '0.500000' '-0.707107'});
model.component('component').geom('geometry').feature('top_outlet_selection1').set('condition', 'allvertices');
model.component('component').geom('geometry').create('bottom_outlet_selection1', 'CylinderSelection');
model.component('component').geom('geometry').feature('bottom_outlet_selection1').set('entitydim', 2);
model.component('component').geom('geometry').feature('bottom_outlet_selection1').label('Bottom Outlet Selection 1');
model.component('component').geom('geometry').feature('bottom_outlet_selection1').set('r', 0.039);
model.component('component').geom('geometry').feature('bottom_outlet_selection1').set('rin', 0.024);
model.component('component').geom('geometry').feature('bottom_outlet_selection1').set('top', 0.001);
model.component('component').geom('geometry').feature('bottom_outlet_selection1').set('bottom', -0.001);
model.component('component').geom('geometry').feature('bottom_outlet_selection1').set('pos', {'160.000000' '160.000000' '-226.274170'});
model.component('component').geom('geometry').feature('bottom_outlet_selection1').set('axis', {'0.500000' '0.500000' '-0.707107'});
model.component('component').geom('geometry').feature('bottom_outlet_selection1').set('condition', 'allvertices');
model.component('component').geom('geometry').create('bottom_inlet_selection1', 'CylinderSelection');
model.component('component').geom('geometry').feature('bottom_inlet_selection1').set('entitydim', 2);
model.component('component').geom('geometry').feature('bottom_inlet_selection1').label('Bottom Inlet Selection 1');
model.component('component').geom('geometry').feature('bottom_inlet_selection1').set('r', 0.017);
model.component('component').geom('geometry').feature('bottom_inlet_selection1').set('top', 0.001);
model.component('component').geom('geometry').feature('bottom_inlet_selection1').set('bottom', -0.001);
model.component('component').geom('geometry').feature('bottom_inlet_selection1').set('pos', {'160.000000' '160.000000' '-226.274170'});
model.component('component').geom('geometry').feature('bottom_inlet_selection1').set('axis', {'0.500000' '0.500000' '-0.707107'});
model.component('component').geom('geometry').feature('bottom_inlet_selection1').set('condition', 'allvertices');
model.component('component').geom('geometry').run;
model.component('component').geom('geometry').run('blk1');

model.component('component').variable.create('component_variables');
model.component('component').variable('component_variables').set('T_outlet1', 'top_outlet_average_operator1(T)');
model.component('component').variable('component_variables').set('T_bottom1', 'bottom_outlet_average_operator1(T)');
model.component('component').variable('component_variables').set('A_wall1', 'borehole_wall_integration_operator1(1)');
model.component('component').variable('component_variables').set('Q_wall1', 'symmetry_factor1*borehole_wall_integration_operator1(physics.ndflux)');
model.component('component').variable('component_variables').set('symmetry_factor1', '2*pi*0.038000[m]*300.000000[m]/A_wall1');

model.component('component').cpl.create('borehole_wall_integration_operator1', 'Integration');
model.component('component').cpl.create('top_outlet_average_operator1', 'Average');
model.component('component').cpl.create('bottom_outlet_average_operator1', 'Average');
model.component('component').cpl('borehole_wall_integration_operator1').selection.named('geometry_borehole_wall_selection1');
model.component('component').cpl('top_outlet_average_operator1').selection.named('geometry_top_outlet_selection1');
model.component('component').cpl('bottom_outlet_average_operator1').selection.named('geometry_bottom_outlet_selection1');

model.component('component').physics.create('physics', 'HeatTransfer', 'geometry');
model.component('component').physics('physics').identifier('physics');
model.component('component').physics('physics').create('outer_fluid_physics1', 'FluidHeatTransferModel', 3);
model.component('component').physics('physics').feature('outer_fluid_physics1').selection.named('geometry_outer_fluid_selection1');
model.component('component').physics('physics').create('pipe_wall_physics1', 'SolidHeatTransferModel', 3);
model.component('component').physics('physics').feature('pipe_wall_physics1').selection.named('geometry_pipe_wall_selection1');
model.component('component').physics('physics').create('inner_fluid_physics1', 'FluidHeatTransferModel', 3);
model.component('component').physics('physics').feature('inner_fluid_physics1').selection.named('geometry_inner_fluid_selection1');
model.component('component').physics('physics').create('top_inlet_temperature_bc1', 'TemperatureBoundary', 2);
model.component('component').physics('physics').feature('top_inlet_temperature_bc1').selection.named('geometry_top_inlet_selection1');
model.component('component').physics('physics').create('bottom_inlet_temperature_bc1', 'TemperatureBoundary', 2);
model.component('component').physics('physics').feature('bottom_inlet_temperature_bc1').selection.named('geometry_bottom_inlet_selection1');

model.component('component').mesh('mesh').create('inner_cap_mesh1', 'FreeTri');
model.component('component').mesh('mesh').create('outer_cap_mesh1', 'FreeTri');
model.component('component').mesh('mesh').create('swept_mesh1', 'Sweep');
model.component('component').mesh('mesh').create('cylinders_mesh1', 'FreeTet');
model.component('component').mesh('mesh').create('ftet1', 'FreeTet');
model.component('component').mesh('mesh').feature('inner_cap_mesh1').selection.named('geometry_inner_cap_selection1');
model.component('component').mesh('mesh').feature('inner_cap_mesh1').create('size', 'Size');
model.component('component').mesh('mesh').feature('outer_cap_mesh1').selection.named('geometry_outer_cap_selection1');
model.component('component').mesh('mesh').feature('outer_cap_mesh1').create('size', 'Size');
model.component('component').mesh('mesh').feature('swept_mesh1').selection.named('geometry_borehole_structure_selection1');
model.component('component').mesh('mesh').feature('swept_mesh1').create('distribution', 'Distribution');
model.component('component').mesh('mesh').feature('cylinders_mesh1').selection.named('geometry_cylinders_selection1');
model.component('component').mesh('mesh').feature('cylinders_mesh1').create('size', 'Size');

model.component('component').view('view1').set('renderwireframe', true);

model.component('component').cpl('borehole_wall_integration_operator1').label('Borehole Wall Integration Operator 1');
model.component('component').cpl('top_outlet_average_operator1').label('Top Average Operator 1');
model.component('component').cpl('bottom_outlet_average_operator1').label('Bottom Average Operator 1');

model.component('component').physics('physics').label('Heat Transfer');
model.component('component').physics('physics').prop('ShapeProperty').set('order_temperature', 1);
model.component('component').physics('physics').feature('solid1').set('k_mat', 'userdef');
model.component('component').physics('physics').feature('solid1').set('k', [3; 0; 0; 0; 3; 0; 0; 0; 3]);
model.component('component').physics('physics').feature('solid1').set('rho_mat', 'userdef');
model.component('component').physics('physics').feature('solid1').set('rho', 2700);
model.component('component').physics('physics').feature('solid1').set('Cp_mat', 'userdef');
model.component('component').physics('physics').feature('solid1').set('Cp', 730);
model.component('component').physics('physics').feature('solid1').label('Bedrock Physics');
model.component('component').physics('physics').feature('init1').set('Tinit', 'T_initial(z)');
model.component('component').physics('physics').feature('init1').label('Initial Values');
model.component('component').physics('physics').feature('outer_fluid_physics1').set('k_mat', 'userdef');
model.component('component').physics('physics').feature('outer_fluid_physics1').set('k', {'750.145060'; '-249.854940'; '353.348245'; '-249.854940'; '750.145060'; '353.348245'; '353.348245'; '353.348245'; '500.290120'});
model.component('component').physics('physics').feature('outer_fluid_physics1').set('rho_mat', 'userdef');
model.component('component').physics('physics').feature('outer_fluid_physics1').set('rho', 999.7587686101307);
model.component('component').physics('physics').feature('outer_fluid_physics1').set('Cp_mat', 'userdef');
model.component('component').physics('physics').feature('outer_fluid_physics1').set('Cp', 4189.895315737093);
model.component('component').physics('physics').feature('outer_fluid_physics1').set('gamma_mat', 'userdef');
model.component('component').physics('physics').feature('outer_fluid_physics1').set('u', [0.116597; 0.116597; -0.164893]);
model.component('component').physics('physics').feature('outer_fluid_physics1').label('Outer Fluid Physics 1');
model.component('component').physics('physics').feature('pipe_wall_physics1').set('k_mat', 'userdef');
model.component('component').physics('physics').feature('pipe_wall_physics1').set('k', {'0.100000'; '0.000000'; '0.000000'; '0.000000'; '0.100000'; '0.000000'; '0.000000'; '0.000000'; '0.100000'});
model.component('component').physics('physics').feature('pipe_wall_physics1').set('rho_mat', 'userdef');
model.component('component').physics('physics').feature('pipe_wall_physics1').set('rho', 900);
model.component('component').physics('physics').feature('pipe_wall_physics1').set('Cp_mat', 'userdef');
model.component('component').physics('physics').feature('pipe_wall_physics1').set('Cp', 1900);
model.component('component').physics('physics').feature('pipe_wall_physics1').label('Pipe Wall Physics 1');
model.component('component').physics('physics').feature('inner_fluid_physics1').set('k_mat', 'userdef');
model.component('component').physics('physics').feature('inner_fluid_physics1').set('k', {'750.145060'; '-249.854940'; '353.348245'; '-249.854940'; '750.145060'; '353.348245'; '353.348245'; '353.348245'; '500.290120'});
model.component('component').physics('physics').feature('inner_fluid_physics1').set('rho_mat', 'userdef');
model.component('component').physics('physics').feature('inner_fluid_physics1').set('rho', 999.7587686101307);
model.component('component').physics('physics').feature('inner_fluid_physics1').set('Cp_mat', 'userdef');
model.component('component').physics('physics').feature('inner_fluid_physics1').set('Cp', 4189.895315737093);
model.component('component').physics('physics').feature('inner_fluid_physics1').set('gamma_mat', 'userdef');
model.component('component').physics('physics').feature('inner_fluid_physics1').set('u', [-0.373019; -0.373019; 0.527529]);
model.component('component').physics('physics').feature('inner_fluid_physics1').label('Inner Fluid Physics 1');
model.component('component').physics('physics').feature('top_inlet_temperature_bc1').set('T0', 'T_inlet');
model.component('component').physics('physics').feature('top_inlet_temperature_bc1').label('Top Inlet Temperature BC 1');
model.component('component').physics('physics').feature('bottom_inlet_temperature_bc1').set('T0', 'T_bottom1');
model.component('component').physics('physics').feature('bottom_inlet_temperature_bc1').label('Bottom Inlet Temperature BC 1');

model.component('component').mesh('mesh').feature('inner_cap_mesh1').label('Inner Cap Mesh 1');
model.component('component').mesh('mesh').feature('inner_cap_mesh1').feature('size').set('hauto', 1);
model.component('component').mesh('mesh').feature('inner_cap_mesh1').feature('size').set('custom', 'on');
model.component('component').mesh('mesh').feature('inner_cap_mesh1').feature('size').set('hmax', 0.015);
model.component('component').mesh('mesh').feature('inner_cap_mesh1').feature('size').set('hmaxactive', true);
model.component('component').mesh('mesh').feature('inner_cap_mesh1').feature('size').set('hmin', 0.0427);
model.component('component').mesh('mesh').feature('inner_cap_mesh1').feature('size').set('hminactive', false);
model.component('component').mesh('mesh').feature('outer_cap_mesh1').label('Outer Cap Mesh 1');
model.component('component').mesh('mesh').feature('outer_cap_mesh1').feature('size').set('hauto', 1);
model.component('component').mesh('mesh').feature('outer_cap_mesh1').feature('size').set('custom', 'on');
model.component('component').mesh('mesh').feature('outer_cap_mesh1').feature('size').set('hmax', 0.1);
model.component('component').mesh('mesh').feature('outer_cap_mesh1').feature('size').set('hmaxactive', true);
model.component('component').mesh('mesh').feature('outer_cap_mesh1').feature('size').set('hmin', 0.0427);
model.component('component').mesh('mesh').feature('outer_cap_mesh1').feature('size').set('hgrad', 1.2);
model.component('component').mesh('mesh').feature('outer_cap_mesh1').feature('size').set('hgradactive', true);
model.component('component').mesh('mesh').feature('outer_cap_mesh1').feature('size').set('hminactive', false);
model.component('component').mesh('mesh').feature('swept_mesh1').label('Swept Mesh 1');
model.component('component').mesh('mesh').feature('swept_mesh1').feature('distribution').set('type', 'predefined');
model.component('component').mesh('mesh').feature('swept_mesh1').feature('distribution').set('elemcount', 300);
model.component('component').mesh('mesh').feature('swept_mesh1').feature('distribution').set('elemratio', 10);
model.component('component').mesh('mesh').feature('swept_mesh1').feature('distribution').set('symmetric', true);
model.component('component').mesh('mesh').feature('cylinders_mesh1').label('Cylinders Mesh 1');
model.component('component').mesh('mesh').feature('cylinders_mesh1').feature('size').set('hauto', 3);
model.component('component').mesh('mesh').feature('ftet1').label('Free Tetrahedral 1');
model.component('component').mesh('mesh').run;

model.study.create('std1');
model.study('std1').create('time', 'Transient');

model.sol.create('sol1');
model.sol('sol1').study('std1');
model.sol('sol1').attach('std1');
model.sol('sol1').create('st1', 'StudyStep');
model.sol('sol1').create('v1', 'Variables');
model.sol('sol1').create('t1', 'Time');
model.sol('sol1').feature('t1').create('fc1', 'FullyCoupled');
model.sol('sol1').feature('t1').create('d1', 'Direct');
model.sol('sol1').feature('t1').create('i1', 'Iterative');
model.sol('sol1').feature('t1').create('i2', 'Iterative');
model.sol('sol1').feature('t1').feature('i1').create('mg1', 'Multigrid');
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('pr').create('so1', 'SOR');
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('po').create('so1', 'SOR');
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('cs').create('d1', 'Direct');
model.sol('sol1').feature('t1').feature('i2').create('mg1', 'Multigrid');
model.sol('sol1').feature('t1').feature('i2').feature('mg1').feature('pr').create('so1', 'SOR');
model.sol('sol1').feature('t1').feature('i2').feature('mg1').feature('po').create('so1', 'SOR');
model.sol('sol1').feature('t1').feature('i2').feature('mg1').feature('cs').create('d1', 'Direct');
model.sol('sol1').feature('t1').feature.remove('fcDef');

model.result.create('pg1', 'PlotGroup3D');
model.result.create('pg2', 'PlotGroup3D');
model.result.create('pg3', 'PlotGroup3D');
model.result.create('pg4', 'PlotGroup1D');
model.result.create('pg5', 'PlotGroup1D');
model.result('pg1').create('surf1', 'Surface');
model.result('pg2').create('iso1', 'Isosurface');
model.result('pg3').create('slc1', 'Slice');
model.result('pg4').create('glob1', 'Global');
model.result('pg5').create('lngr1', 'LineGraph');
model.result('pg5').create('lngr2', 'LineGraph');
model.result('pg5').feature('lngr1').selection.set([44]);
model.result('pg5').feature('lngr2').selection.set([31]);

model.study('std1').feature('time').set('tunit', 'd');
model.study('std1').feature('time').set('tlist', '0 10');

model.sol('sol1').attach('std1');
model.sol('sol1').feature('v1').set('clist', {'0 10' '0.01[d]'});
model.sol('sol1').feature('t1').set('tunit', 'd');
model.sol('sol1').feature('t1').set('tlist', '0 10');
model.sol('sol1').feature('t1').set('maxorder', 2);
model.sol('sol1').feature('t1').set('estrat', 'exclude');
model.sol('sol1').feature('t1').set('tout', 'tsteps');
model.sol('sol1').feature('t1').feature('fc1').set('linsolver', 'd1');
model.sol('sol1').feature('t1').feature('fc1').set('maxiter', 5);
model.sol('sol1').feature('t1').feature('fc1').set('damp', 0.9);
model.sol('sol1').feature('t1').feature('fc1').set('jtech', 'once');
model.sol('sol1').feature('t1').feature('fc1').set('stabacc', 'aacc');
model.sol('sol1').feature('t1').feature('fc1').set('aaccdim', 5);
model.sol('sol1').feature('t1').feature('fc1').set('aaccmix', 0.9);
model.sol('sol1').feature('t1').feature('fc1').set('aaccdelay', 1);
model.sol('sol1').feature('t1').feature('d1').label('Direct, Heat Transfer Variables (physics)');
model.sol('sol1').feature('t1').feature('d1').set('linsolver', 'pardiso');
model.sol('sol1').feature('t1').feature('d1').set('pivotperturb', 1.0E-13);
model.sol('sol1').feature('t1').feature('i1').label('AMG, Heat Transfer Variables (physics)');
model.sol('sol1').feature('t1').feature('i1').feature('mg1').set('prefun', 'saamg');
model.sol('sol1').feature('t1').feature('i1').feature('mg1').set('saamgcompwise', true);
model.sol('sol1').feature('t1').feature('i1').feature('mg1').set('usesmooth', false);
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('pr').feature('so1').set('relax', 0.9);
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('po').feature('so1').set('relax', 0.9);
model.sol('sol1').feature('t1').feature('i1').feature('mg1').feature('cs').feature('d1').set('linsolver', 'pardiso');
model.sol('sol1').feature('t1').feature('i2').label('GMG, Heat Transfer Variables (physics)');
model.sol('sol1').feature('t1').feature('i2').set('rhob', 20);
model.sol('sol1').feature('t1').feature('i2').feature('mg1').feature('cs').feature('d1').set('linsolver', 'pardiso');
model.sol('sol1').runAll;

model.result('pg1').label('Temperature (physics)');
model.result('pg1').feature('surf1').label('Surface');
model.result('pg1').feature('surf1').set('colortable', 'ThermalLight');
model.result('pg1').feature('surf1').set('resolution', 'normal');
model.result('pg2').label('Isothermal Contours (physics)');
model.result('pg2').feature('iso1').label('Isosurface');
model.result('pg2').feature('iso1').set('number', 10);
model.result('pg2').feature('iso1').set('levelrounding', false);
model.result('pg2').feature('iso1').set('colortable', 'ThermalLight');
model.result('pg2').feature('iso1').set('resolution', 'normal');
model.result('pg3').feature('slc1').set('unit', 'degC');
model.result('pg3').feature('slc1').set('quickxnumber', 1);
model.result('pg3').feature('slc1').set('resolution', 'normal');
model.result('pg4').set('xlabel', 'Time (d)');
model.result('pg4').set('xlabelactive', false);
model.result('pg4').feature('glob1').set('expr', {'Q_wall1' '0.6[L/s]*1900[J/(m*K)]*(T_outlet1-T_inlet)'});
model.result('pg4').feature('glob1').set('unit', {'W' 'kg*m^4/s^3'});
model.result('pg4').feature('glob1').set('descr', {'' ''});
model.result('pg5').set('looplevelinput', {'interp'});
model.result('pg5').set('interp', [10]);
model.result('pg5').set('xlabel', 'Arc length (m)');
model.result('pg5').set('ylabel', 'Temperature (degC)');
model.result('pg5').set('xlabelactive', false);
model.result('pg5').set('ylabelactive', false);
model.result('pg5').feature('lngr1').set('unit', 'degC');
model.result('pg5').feature('lngr1').set('resolution', 'normal');
model.result('pg5').feature('lngr2').set('unit', 'degC');
model.result('pg5').feature('lngr2').set('resolution', 'normal');

out = model;
