function out = model
%
% temp.m
%
% Model exported on Jan 27 2020, 18:39 by COMSOL 5.5.0.292.

import com.comsol.model.*
import com.comsol.model.util.*

model = ModelUtil.create('Model');

model.modelPath('E:\Work\Energiakaivos\Code');

model.label('fan_model_3d');

model.component.create('component', true);

model.component('component').geom.create('geometry', 3);

model.component('component').mesh.create('mesh');

model.component('component').geom('geometry').create('work_plane1_borehole_structure', 'WorkPlane');
model.component('component').geom('geometry').feature('work_plane1_borehole_structure').label('Borehole Structure Work Plane 1');
model.component('component').geom('geometry').feature('work_plane1_borehole_structure').set('planetype', 'normalvector');
model.component('component').geom('geometry').feature('work_plane1_borehole_structure').set('normalcoord', {'0.000000' '0.000000' '0.000000'});
model.component('component').geom('geometry').feature('work_plane1_borehole_structure').set('normalvector', {'0.000000' '0.000000' '-1.000000'});
model.component('component').geom('geometry').feature('work_plane1_borehole_structure').set('unite', true);
model.component('component').geom('geometry').feature('work_plane1_borehole_structure').geom.create('circle1', 'Circle');
model.component('component').geom('geometry').feature('work_plane1_borehole_structure').geom.feature('circle1').label('Circle 1');
model.component('component').geom('geometry').feature('work_plane1_borehole_structure').geom.feature('circle1').set('r', 0.5);
model.component('component').geom('geometry').feature('work_plane1_borehole_structure').geom.create('circle2', 'Circle');
model.component('component').geom('geometry').feature('work_plane1_borehole_structure').geom.feature('circle2').label('Circle 2');
model.component('component').geom('geometry').feature('work_plane1_borehole_structure').geom.feature('circle2').set('r', 0.1);
model.component('component').geom('geometry').feature('work_plane1_borehole_structure').geom.create('circle3', 'Circle');
model.component('component').geom('geometry').feature('work_plane1_borehole_structure').geom.feature('circle3').label('Circle 3');
model.component('component').geom('geometry').feature('work_plane1_borehole_structure').geom.feature('circle3').set('r', 0.08);
model.component('component').geom('geometry').feature('work_plane1_borehole_structure').geom.create('circle4', 'Circle');
model.component('component').geom('geometry').feature('work_plane1_borehole_structure').geom.feature('circle4').label('Circle 4');
model.component('component').geom('geometry').feature('work_plane1_borehole_structure').geom.feature('circle4').set('r', 0.05);
model.component('component').geom('geometry').create('buffer_zone_selection1', 'CylinderSelection');
model.component('component').geom('geometry').feature('buffer_zone_selection1').label('Buffer Zone Selection 1');
model.component('component').geom('geometry').feature('buffer_zone_selection1').set('r', 0.501);
model.component('component').geom('geometry').feature('buffer_zone_selection1').set('rin', 0.099);
model.component('component').geom('geometry').feature('buffer_zone_selection1').set('top', 100.001);
model.component('component').geom('geometry').feature('buffer_zone_selection1').set('bottom', -0.001);
model.component('component').geom('geometry').feature('buffer_zone_selection1').set('pos', {'0.000000' '0.000000' '0.000000'});
model.component('component').geom('geometry').feature('buffer_zone_selection1').set('axis', {'0.000000' '0.000000' '-1.000000'});
model.component('component').geom('geometry').feature('buffer_zone_selection1').set('condition', 'allvertices');
model.component('component').geom('geometry').create('outer_fluid_selection1', 'CylinderSelection');
model.component('component').geom('geometry').feature('outer_fluid_selection1').label('Outer Fluid Selection 1');
model.component('component').geom('geometry').feature('outer_fluid_selection1').set('r', 0.101);
model.component('component').geom('geometry').feature('outer_fluid_selection1').set('rin', 0.079);
model.component('component').geom('geometry').feature('outer_fluid_selection1').set('top', 100.001);
model.component('component').geom('geometry').feature('outer_fluid_selection1').set('bottom', -0.001);
model.component('component').geom('geometry').feature('outer_fluid_selection1').set('pos', {'0.000000' '0.000000' '0.000000'});
model.component('component').geom('geometry').feature('outer_fluid_selection1').set('axis', {'0.000000' '0.000000' '-1.000000'});
model.component('component').geom('geometry').feature('outer_fluid_selection1').set('condition', 'allvertices');
model.component('component').geom('geometry').create('pipe_wall_selection1', 'CylinderSelection');
model.component('component').geom('geometry').feature('pipe_wall_selection1').label('Pipe Wall Selection 1');
model.component('component').geom('geometry').feature('pipe_wall_selection1').set('r', 0.081);
model.component('component').geom('geometry').feature('pipe_wall_selection1').set('rin', 0.001);
model.component('component').geom('geometry').feature('pipe_wall_selection1').set('top', 100.001);
model.component('component').geom('geometry').feature('pipe_wall_selection1').set('bottom', -0.001);
model.component('component').geom('geometry').feature('pipe_wall_selection1').set('pos', {'0.000000' '0.000000' '0.000000'});
model.component('component').geom('geometry').feature('pipe_wall_selection1').set('axis', {'0.000000' '0.000000' '-1.000000'});
model.component('component').geom('geometry').feature('pipe_wall_selection1').set('condition', 'inside');
model.component('component').geom('geometry').create('inner_fluid_selection1', 'CylinderSelection');
model.component('component').geom('geometry').feature('inner_fluid_selection1').label('Inner Fluid Selection 1');
model.component('component').geom('geometry').feature('inner_fluid_selection1').set('r', 0.051000000000000004);
model.component('component').geom('geometry').feature('inner_fluid_selection1').set('rin', '0');
model.component('component').geom('geometry').feature('inner_fluid_selection1').set('top', 100.001);
model.component('component').geom('geometry').feature('inner_fluid_selection1').set('bottom', -0.001);
model.component('component').geom('geometry').feature('inner_fluid_selection1').set('pos', {'0.000000' '0.000000' '0.000000'});
model.component('component').geom('geometry').feature('inner_fluid_selection1').set('axis', {'0.000000' '0.000000' '-1.000000'});
model.component('component').geom('geometry').feature('inner_fluid_selection1').set('condition', 'allvertices');
model.component('component').geom('geometry').create('borehole_structure_selection1', 'UnionSelection');
model.component('component').geom('geometry').feature('borehole_structure_selection1').set('input', {'buffer_zone_selection1' 'outer_fluid_selection1' 'pipe_wall_selection1' 'inner_fluid_selection1'});
model.component('component').geom('geometry').create('borehole_wall_selection1', 'CylinderSelection');
model.component('component').geom('geometry').feature('borehole_wall_selection1').label('Borehole Wall Selection 1');
model.component('component').geom('geometry').feature('borehole_wall_selection1').set('entitydim', 2);
model.component('component').geom('geometry').feature('borehole_wall_selection1').set('r', 0.101);
model.component('component').geom('geometry').feature('borehole_wall_selection1').set('rin', 0.099);
model.component('component').geom('geometry').feature('borehole_wall_selection1').set('top', 100.001);
model.component('component').geom('geometry').feature('borehole_wall_selection1').set('bottom', -0.001);
model.component('component').geom('geometry').feature('borehole_wall_selection1').set('pos', {'0.000000' '0.000000' '0.000000'});
model.component('component').geom('geometry').feature('borehole_wall_selection1').set('axis', {'0.000000' '0.000000' '-1.000000'});
model.component('component').geom('geometry').feature('borehole_wall_selection1').set('condition', 'allvertices');
model.component('component').geom('geometry').create('upper_cylinder_selection1', 'CylinderSelection');
model.component('component').geom('geometry').feature('upper_cylinder_selection1').label('Upper Cylinder Selection 1');
model.component('component').geom('geometry').feature('upper_cylinder_selection1').set('r', 0.501);
model.component('component').geom('geometry').feature('upper_cylinder_selection1').set('rin', '0');
model.component('component').geom('geometry').feature('upper_cylinder_selection1').set('top', 0.501);
model.component('component').geom('geometry').feature('upper_cylinder_selection1').set('bottom', -0.001);
model.component('component').geom('geometry').feature('upper_cylinder_selection1').set('pos', {'-0.000000' '0.000000' '0.500000'});
model.component('component').geom('geometry').feature('upper_cylinder_selection1').set('axis', {'0.000000' '0.000000' '-1.000000'});
model.component('component').geom('geometry').feature('upper_cylinder_selection1').set('condition', 'allvertices');
model.component('component').geom('geometry').create('lower_cylinder_selection1', 'CylinderSelection');
model.component('component').geom('geometry').feature('lower_cylinder_selection1').label('Lower Cylinder Selection 1');
model.component('component').geom('geometry').feature('lower_cylinder_selection1').set('r', 0.501);
model.component('component').geom('geometry').feature('lower_cylinder_selection1').set('rin', '0');
model.component('component').geom('geometry').feature('lower_cylinder_selection1').set('top', 0.501);
model.component('component').geom('geometry').feature('lower_cylinder_selection1').set('bottom', -0.001);
model.component('component').geom('geometry').feature('lower_cylinder_selection1').set('pos', {'0.000000' '0.000000' '-100.000000'});
model.component('component').geom('geometry').feature('lower_cylinder_selection1').set('axis', {'0.000000' '0.000000' '-1.000000'});
model.component('component').geom('geometry').feature('lower_cylinder_selection1').set('condition', 'allvertices');
model.component('component').geom('geometry').create('cylinders_selection1', 'UnionSelection');
model.component('component').geom('geometry').feature('cylinders_selection1').set('input', {'upper_cylinder_selection1' 'lower_cylinder_selection1'});
model.component('component').geom('geometry').create('outer_cap_selection1', 'CylinderSelection');
model.component('component').geom('geometry').feature('outer_cap_selection1').label('Outer Cap Selection 1');
model.component('component').geom('geometry').feature('outer_cap_selection1').set('entitydim', 2);
model.component('component').geom('geometry').feature('outer_cap_selection1').set('r', 0.501);
model.component('component').geom('geometry').feature('outer_cap_selection1').set('rin', 0.099);
model.component('component').geom('geometry').feature('outer_cap_selection1').set('top', 0.001);
model.component('component').geom('geometry').feature('outer_cap_selection1').set('bottom', -0.001);
model.component('component').geom('geometry').feature('outer_cap_selection1').set('pos', {'0.000000' '0.000000' '0.000000'});
model.component('component').geom('geometry').feature('outer_cap_selection1').set('axis', {'0.000000' '0.000000' '-1.000000'});
model.component('component').geom('geometry').feature('outer_cap_selection1').set('condition', 'inside');
model.component('component').geom('geometry').create('inner_cap_selection1', 'CylinderSelection');
model.component('component').geom('geometry').feature('inner_cap_selection1').label('Inner Cap Selection 1');
model.component('component').geom('geometry').feature('inner_cap_selection1').set('entitydim', 2);
model.component('component').geom('geometry').feature('inner_cap_selection1').set('r', 0.101);
model.component('component').geom('geometry').feature('inner_cap_selection1').set('rin', 0);
model.component('component').geom('geometry').feature('inner_cap_selection1').set('top', 0.001);
model.component('component').geom('geometry').feature('inner_cap_selection1').set('bottom', -0.001);
model.component('component').geom('geometry').feature('inner_cap_selection1').set('pos', {'0.000000' '0.000000' '0.000000'});
model.component('component').geom('geometry').feature('inner_cap_selection1').set('axis', {'0.000000' '0.000000' '-1.000000'});
model.component('component').geom('geometry').feature('inner_cap_selection1').set('condition', 'allvertices');
model.component('component').geom('geometry').create('top_inlet_selection1', 'CylinderSelection');
model.component('component').geom('geometry').feature('top_inlet_selection1').label('Top Inlet Selection 1');
model.component('component').geom('geometry').feature('top_inlet_selection1').set('entitydim', 2);
model.component('component').geom('geometry').feature('top_inlet_selection1').set('r', 0.101);
model.component('component').geom('geometry').feature('top_inlet_selection1').set('rin', 0.079);
model.component('component').geom('geometry').feature('top_inlet_selection1').set('top', 0.001);
model.component('component').geom('geometry').feature('top_inlet_selection1').set('bottom', -0.001);
model.component('component').geom('geometry').feature('top_inlet_selection1').set('pos', {'0.000000' '0.000000' '0.000000'});
model.component('component').geom('geometry').feature('top_inlet_selection1').set('axis', {'0.000000' '0.000000' '-1.000000'});
model.component('component').geom('geometry').feature('top_inlet_selection1').set('condition', 'allvertices');
model.component('component').geom('geometry').create('top_outlet_selection1', 'CylinderSelection');
model.component('component').geom('geometry').feature('top_outlet_selection1').label('Top Outlet Selection 1');
model.component('component').geom('geometry').feature('top_outlet_selection1').set('entitydim', 2);
model.component('component').geom('geometry').feature('top_outlet_selection1').set('r', 0.051000000000000004);
model.component('component').geom('geometry').feature('top_outlet_selection1').set('rin', '0');
model.component('component').geom('geometry').feature('top_outlet_selection1').set('top', 0.001);
model.component('component').geom('geometry').feature('top_outlet_selection1').set('bottom', -0.001);
model.component('component').geom('geometry').feature('top_outlet_selection1').set('pos', {'0.000000' '0.000000' '0.000000'});
model.component('component').geom('geometry').feature('top_outlet_selection1').set('axis', {'0.000000' '0.000000' '-1.000000'});
model.component('component').geom('geometry').feature('top_outlet_selection1').set('condition', 'allvertices');
model.component('component').geom('geometry').create('bottom_outlet_selection1', 'CylinderSelection');
model.component('component').geom('geometry').feature('bottom_outlet_selection1').label('Bottom Outlet Selection 1');
model.component('component').geom('geometry').feature('bottom_outlet_selection1').set('entitydim', 2);
model.component('component').geom('geometry').feature('bottom_outlet_selection1').set('r', 0.101);
model.component('component').geom('geometry').feature('bottom_outlet_selection1').set('rin', 0.079);
model.component('component').geom('geometry').feature('bottom_outlet_selection1').set('top', 0.001);
model.component('component').geom('geometry').feature('bottom_outlet_selection1').set('bottom', -0.001);
model.component('component').geom('geometry').feature('bottom_outlet_selection1').set('pos', {'0.000000' '0.000000' '-100.000000'});
model.component('component').geom('geometry').feature('bottom_outlet_selection1').set('axis', {'0.000000' '0.000000' '-1.000000'});
model.component('component').geom('geometry').feature('bottom_outlet_selection1').set('condition', 'allvertices');
model.component('component').geom('geometry').create('bottom_inlet_selection1', 'CylinderSelection');
model.component('component').geom('geometry').feature('bottom_inlet_selection1').label('Bottom Inlet Selection 1');
model.component('component').geom('geometry').feature('bottom_inlet_selection1').set('entitydim', 2);
model.component('component').geom('geometry').feature('bottom_inlet_selection1').set('r', 0.051000000000000004);
model.component('component').geom('geometry').feature('bottom_inlet_selection1').set('rin', '0');
model.component('component').geom('geometry').feature('bottom_inlet_selection1').set('top', 0.001);
model.component('component').geom('geometry').feature('bottom_inlet_selection1').set('bottom', -0.001);
model.component('component').geom('geometry').feature('bottom_inlet_selection1').set('pos', {'0.000000' '0.000000' '-100.000000'});
model.component('component').geom('geometry').feature('bottom_inlet_selection1').set('axis', {'0.000000' '0.000000' '-1.000000'});
model.component('component').geom('geometry').feature('bottom_inlet_selection1').set('condition', 'allvertices');

model.component('component').mesh('mesh').create('inner_cap_mesh1', 'FreeTri');
model.component('component').mesh('mesh').feature('inner_cap_mesh1').label('Inner Cap Mesh 1');
model.component('component').mesh('mesh').feature('inner_cap_mesh1').selection.named('geometry_inner_cap_selection1');
model.component('component').mesh('mesh').feature('inner_cap_mesh1').create('size', 'Size');
model.component('component').mesh('mesh').feature('inner_cap_mesh1').feature('size').set('hauto', 1);
model.component('component').mesh('mesh').feature('inner_cap_mesh1').feature('size').set('custom', true);
model.component('component').mesh('mesh').feature('inner_cap_mesh1').feature('size').set('hmax', 0.015);
model.component('component').mesh('mesh').feature('inner_cap_mesh1').feature('size').set('hmaxactive', true);
model.component('component').mesh('mesh').create('outer_cap_mesh1', 'FreeTri');
model.component('component').mesh('mesh').feature('outer_cap_mesh1').label('Outer Cap Mesh 1');
model.component('component').mesh('mesh').feature('outer_cap_mesh1').selection.named('geometry_outer_cap_selection1');
model.component('component').mesh('mesh').feature('outer_cap_mesh1').create('size', 'Size');
model.component('component').mesh('mesh').feature('outer_cap_mesh1').feature('size').set('hauto', 1);
model.component('component').mesh('mesh').feature('outer_cap_mesh1').feature('size').set('custom', 'on');
model.component('component').mesh('mesh').feature('outer_cap_mesh1').feature('size').set('hgrad', 1.2);
model.component('component').mesh('mesh').feature('outer_cap_mesh1').feature('size').set('hgradactive', true);
model.component('component').mesh('mesh').feature('outer_cap_mesh1').feature('size').set('hmax', 0.1);
model.component('component').mesh('mesh').feature('outer_cap_mesh1').feature('size').set('hmaxactive', true);
model.component('component').mesh('mesh').create('swept_mesh1', 'Sweep');
model.component('component').mesh('mesh').feature('swept_mesh1').label('Swept Mesh 1');
model.component('component').mesh('mesh').feature('swept_mesh1').selection.geom('geometry', 3);
model.component('component').mesh('mesh').feature('swept_mesh1').selection.named('geometry_borehole_structure_selection1');
model.component('component').mesh('mesh').feature('swept_mesh1').create('distribution', 'Distribution');
model.component('component').mesh('mesh').feature('swept_mesh1').feature('distribution').set('type', 'predefined');
model.component('component').mesh('mesh').feature('swept_mesh1').feature('distribution').set('elemcount', 300);
model.component('component').mesh('mesh').feature('swept_mesh1').feature('distribution').set('elemratio', 10);
model.component('component').mesh('mesh').feature('swept_mesh1').feature('distribution').set('symmetric', true);
model.component('component').mesh('mesh').create('cylinders_mesh1', 'FreeTet');
model.component('component').mesh('mesh').feature('cylinders_mesh1').label('Cylinders Mesh 1');
model.component('component').mesh('mesh').feature('cylinders_mesh1').selection.geom('geometry', 3);
model.component('component').mesh('mesh').feature('cylinders_mesh1').selection.named('geometry_cylinders_selection1');
model.component('component').mesh('mesh').feature('cylinders_mesh1').create('size', 'Size');
model.component('component').mesh('mesh').feature('cylinders_mesh1').feature('size').set('hauto', 3);

model.component('component').geom('geometry').create('work_plane2_borehole_structure', 'WorkPlane');
model.component('component').geom('geometry').feature('work_plane2_borehole_structure').label('Borehole Structure Work Plane 2');
model.component('component').geom('geometry').feature('work_plane2_borehole_structure').set('planetype', 'normalvector');
model.component('component').geom('geometry').feature('work_plane2_borehole_structure').set('normalcoord', {'50.000000' '50.000000' '0.000000'});
model.component('component').geom('geometry').feature('work_plane2_borehole_structure').set('normalvector', {'0.500000' '0.500000' '-0.707107'});
model.component('component').geom('geometry').feature('work_plane2_borehole_structure').set('unite', true);
model.component('component').geom('geometry').feature('work_plane2_borehole_structure').geom.create('circle1', 'Circle');
model.component('component').geom('geometry').feature('work_plane2_borehole_structure').geom.feature('circle1').label('Circle 1');
model.component('component').geom('geometry').feature('work_plane2_borehole_structure').geom.feature('circle1').set('r', 0.5);
model.component('component').geom('geometry').feature('work_plane2_borehole_structure').geom.create('circle2', 'Circle');
model.component('component').geom('geometry').feature('work_plane2_borehole_structure').geom.feature('circle2').label('Circle 2');
model.component('component').geom('geometry').feature('work_plane2_borehole_structure').geom.feature('circle2').set('r', 0.1);
model.component('component').geom('geometry').feature('work_plane2_borehole_structure').geom.create('circle3', 'Circle');
model.component('component').geom('geometry').feature('work_plane2_borehole_structure').geom.feature('circle3').label('Circle 3');
model.component('component').geom('geometry').feature('work_plane2_borehole_structure').geom.feature('circle3').set('r', 0.08);
model.component('component').geom('geometry').feature('work_plane2_borehole_structure').geom.create('circle4', 'Circle');
model.component('component').geom('geometry').feature('work_plane2_borehole_structure').geom.feature('circle4').label('Circle 4');
model.component('component').geom('geometry').feature('work_plane2_borehole_structure').geom.feature('circle4').set('r', 0.05);
model.component('component').geom('geometry').create('buffer_zone_selection2', 'CylinderSelection');
model.component('component').geom('geometry').feature('buffer_zone_selection2').label('Buffer Zone Selection 2');
model.component('component').geom('geometry').feature('buffer_zone_selection2').set('r', 0.501);
model.component('component').geom('geometry').feature('buffer_zone_selection2').set('rin', 0.099);
model.component('component').geom('geometry').feature('buffer_zone_selection2').set('top', 100.001);
model.component('component').geom('geometry').feature('buffer_zone_selection2').set('bottom', -0.001);
model.component('component').geom('geometry').feature('buffer_zone_selection2').set('pos', {'50.000000' '50.000000' '0.000000'});
model.component('component').geom('geometry').feature('buffer_zone_selection2').set('axis', {'0.500000' '0.500000' '-0.707107'});
model.component('component').geom('geometry').feature('buffer_zone_selection2').set('condition', 'allvertices');
model.component('component').geom('geometry').create('outer_fluid_selection2', 'CylinderSelection');
model.component('component').geom('geometry').feature('outer_fluid_selection2').label('Outer Fluid Selection 2');
model.component('component').geom('geometry').feature('outer_fluid_selection2').set('r', 0.101);
model.component('component').geom('geometry').feature('outer_fluid_selection2').set('rin', 0.079);
model.component('component').geom('geometry').feature('outer_fluid_selection2').set('top', 100.001);
model.component('component').geom('geometry').feature('outer_fluid_selection2').set('bottom', -0.001);
model.component('component').geom('geometry').feature('outer_fluid_selection2').set('pos', {'50.000000' '50.000000' '0.000000'});
model.component('component').geom('geometry').feature('outer_fluid_selection2').set('axis', {'0.500000' '0.500000' '-0.707107'});
model.component('component').geom('geometry').feature('outer_fluid_selection2').set('condition', 'allvertices');
model.component('component').geom('geometry').create('pipe_wall_selection2', 'CylinderSelection');
model.component('component').geom('geometry').feature('pipe_wall_selection2').label('Pipe Wall Selection 2');
model.component('component').geom('geometry').feature('pipe_wall_selection2').set('r', 0.081);
model.component('component').geom('geometry').feature('pipe_wall_selection2').set('rin', 0.001);
model.component('component').geom('geometry').feature('pipe_wall_selection2').set('top', 100.001);
model.component('component').geom('geometry').feature('pipe_wall_selection2').set('bottom', -0.001);
model.component('component').geom('geometry').feature('pipe_wall_selection2').set('pos', {'50.000000' '50.000000' '0.000000'});
model.component('component').geom('geometry').feature('pipe_wall_selection2').set('axis', {'0.500000' '0.500000' '-0.707107'});
model.component('component').geom('geometry').feature('pipe_wall_selection2').set('condition', 'inside');
model.component('component').geom('geometry').create('inner_fluid_selection2', 'CylinderSelection');
model.component('component').geom('geometry').feature('inner_fluid_selection2').label('Inner Fluid Selection 2');
model.component('component').geom('geometry').feature('inner_fluid_selection2').set('r', 0.051000000000000004);
model.component('component').geom('geometry').feature('inner_fluid_selection2').set('rin', '0');
model.component('component').geom('geometry').feature('inner_fluid_selection2').set('top', 100.001);
model.component('component').geom('geometry').feature('inner_fluid_selection2').set('bottom', -0.001);
model.component('component').geom('geometry').feature('inner_fluid_selection2').set('pos', {'50.000000' '50.000000' '0.000000'});
model.component('component').geom('geometry').feature('inner_fluid_selection2').set('axis', {'0.500000' '0.500000' '-0.707107'});
model.component('component').geom('geometry').feature('inner_fluid_selection2').set('condition', 'allvertices');
model.component('component').geom('geometry').create('borehole_structure_selection2', 'UnionSelection');
model.component('component').geom('geometry').feature('borehole_structure_selection2').set('input', {'buffer_zone_selection2' 'outer_fluid_selection2' 'pipe_wall_selection2' 'inner_fluid_selection2'});
model.component('component').geom('geometry').create('borehole_wall_selection2', 'CylinderSelection');
model.component('component').geom('geometry').feature('borehole_wall_selection2').label('Borehole Wall Selection 2');
model.component('component').geom('geometry').feature('borehole_wall_selection2').set('entitydim', 2);
model.component('component').geom('geometry').feature('borehole_wall_selection2').set('r', 0.101);
model.component('component').geom('geometry').feature('borehole_wall_selection2').set('rin', 0.099);
model.component('component').geom('geometry').feature('borehole_wall_selection2').set('top', 100.001);
model.component('component').geom('geometry').feature('borehole_wall_selection2').set('bottom', -0.001);
model.component('component').geom('geometry').feature('borehole_wall_selection2').set('pos', {'50.000000' '50.000000' '0.000000'});
model.component('component').geom('geometry').feature('borehole_wall_selection2').set('axis', {'0.500000' '0.500000' '-0.707107'});
model.component('component').geom('geometry').feature('borehole_wall_selection2').set('condition', 'allvertices');
model.component('component').geom('geometry').create('upper_cylinder_selection2', 'CylinderSelection');
model.component('component').geom('geometry').feature('upper_cylinder_selection2').label('Upper Cylinder Selection 2');
model.component('component').geom('geometry').feature('upper_cylinder_selection2').set('r', 0.501);
model.component('component').geom('geometry').feature('upper_cylinder_selection2').set('rin', '0');
model.component('component').geom('geometry').feature('upper_cylinder_selection2').set('top', 0.501);
model.component('component').geom('geometry').feature('upper_cylinder_selection2').set('bottom', -0.001);
model.component('component').geom('geometry').feature('upper_cylinder_selection2').set('pos', {'49.750000' '49.750000' '0.353553'});
model.component('component').geom('geometry').feature('upper_cylinder_selection2').set('axis', {'0.500000' '0.500000' '-0.707107'});
model.component('component').geom('geometry').feature('upper_cylinder_selection2').set('condition', 'allvertices');
model.component('component').geom('geometry').create('lower_cylinder_selection2', 'CylinderSelection');
model.component('component').geom('geometry').feature('lower_cylinder_selection2').label('Lower Cylinder Selection 2');
model.component('component').geom('geometry').feature('lower_cylinder_selection2').set('r', 0.501);
model.component('component').geom('geometry').feature('lower_cylinder_selection2').set('rin', '0');
model.component('component').geom('geometry').feature('lower_cylinder_selection2').set('top', 0.501);
model.component('component').geom('geometry').feature('lower_cylinder_selection2').set('bottom', -0.001);
model.component('component').geom('geometry').feature('lower_cylinder_selection2').set('pos', {'100.000000' '100.000000' '-70.710678'});
model.component('component').geom('geometry').feature('lower_cylinder_selection2').set('axis', {'0.500000' '0.500000' '-0.707107'});
model.component('component').geom('geometry').feature('lower_cylinder_selection2').set('condition', 'allvertices');
model.component('component').geom('geometry').create('cylinders_selection2', 'UnionSelection');
model.component('component').geom('geometry').feature('cylinders_selection2').set('input', {'upper_cylinder_selection2' 'lower_cylinder_selection2'});
model.component('component').geom('geometry').create('outer_cap_selection2', 'CylinderSelection');
model.component('component').geom('geometry').feature('outer_cap_selection2').label('Outer Cap Selection 2');
model.component('component').geom('geometry').feature('outer_cap_selection2').set('entitydim', 2);
model.component('component').geom('geometry').feature('outer_cap_selection2').set('r', 0.501);
model.component('component').geom('geometry').feature('outer_cap_selection2').set('rin', 0.099);
model.component('component').geom('geometry').feature('outer_cap_selection2').set('top', 0.001);
model.component('component').geom('geometry').feature('outer_cap_selection2').set('bottom', -0.001);
model.component('component').geom('geometry').feature('outer_cap_selection2').set('pos', {'50.000000' '50.000000' '0.000000'});
model.component('component').geom('geometry').feature('outer_cap_selection2').set('axis', {'0.500000' '0.500000' '-0.707107'});
model.component('component').geom('geometry').feature('outer_cap_selection2').set('condition', 'inside');
model.component('component').geom('geometry').create('inner_cap_selection2', 'CylinderSelection');
model.component('component').geom('geometry').feature('inner_cap_selection2').label('Inner Cap Selection 2');
model.component('component').geom('geometry').feature('inner_cap_selection2').set('entitydim', 2);
model.component('component').geom('geometry').feature('inner_cap_selection2').set('r', 0.101);
model.component('component').geom('geometry').feature('inner_cap_selection2').set('rin', 0);
model.component('component').geom('geometry').feature('inner_cap_selection2').set('top', 0.001);
model.component('component').geom('geometry').feature('inner_cap_selection2').set('bottom', -0.001);
model.component('component').geom('geometry').feature('inner_cap_selection2').set('pos', {'50.000000' '50.000000' '0.000000'});
model.component('component').geom('geometry').feature('inner_cap_selection2').set('axis', {'0.500000' '0.500000' '-0.707107'});
model.component('component').geom('geometry').feature('inner_cap_selection2').set('condition', 'allvertices');
model.component('component').geom('geometry').create('top_inlet_selection2', 'CylinderSelection');
model.component('component').geom('geometry').feature('top_inlet_selection2').label('Top Inlet Selection 2');
model.component('component').geom('geometry').feature('top_inlet_selection2').set('entitydim', 2);
model.component('component').geom('geometry').feature('top_inlet_selection2').set('r', 0.101);
model.component('component').geom('geometry').feature('top_inlet_selection2').set('rin', 0.079);
model.component('component').geom('geometry').feature('top_inlet_selection2').set('top', 0.001);
model.component('component').geom('geometry').feature('top_inlet_selection2').set('bottom', -0.001);
model.component('component').geom('geometry').feature('top_inlet_selection2').set('pos', {'50.000000' '50.000000' '0.000000'});
model.component('component').geom('geometry').feature('top_inlet_selection2').set('axis', {'0.500000' '0.500000' '-0.707107'});
model.component('component').geom('geometry').feature('top_inlet_selection2').set('condition', 'allvertices');
model.component('component').geom('geometry').create('top_outlet_selection2', 'CylinderSelection');
model.component('component').geom('geometry').feature('top_outlet_selection2').label('Top Outlet Selection 2');
model.component('component').geom('geometry').feature('top_outlet_selection2').set('entitydim', 2);
model.component('component').geom('geometry').feature('top_outlet_selection2').set('r', 0.051000000000000004);
model.component('component').geom('geometry').feature('top_outlet_selection2').set('rin', '0');
model.component('component').geom('geometry').feature('top_outlet_selection2').set('top', 0.001);
model.component('component').geom('geometry').feature('top_outlet_selection2').set('bottom', -0.001);
model.component('component').geom('geometry').feature('top_outlet_selection2').set('pos', {'50.000000' '50.000000' '0.000000'});
model.component('component').geom('geometry').feature('top_outlet_selection2').set('axis', {'0.500000' '0.500000' '-0.707107'});
model.component('component').geom('geometry').feature('top_outlet_selection2').set('condition', 'allvertices');
model.component('component').geom('geometry').create('bottom_outlet_selection2', 'CylinderSelection');
model.component('component').geom('geometry').feature('bottom_outlet_selection2').label('Bottom Outlet Selection 2');
model.component('component').geom('geometry').feature('bottom_outlet_selection2').set('entitydim', 2);
model.component('component').geom('geometry').feature('bottom_outlet_selection2').set('r', 0.101);
model.component('component').geom('geometry').feature('bottom_outlet_selection2').set('rin', 0.079);
model.component('component').geom('geometry').feature('bottom_outlet_selection2').set('top', 0.001);
model.component('component').geom('geometry').feature('bottom_outlet_selection2').set('bottom', -0.001);
model.component('component').geom('geometry').feature('bottom_outlet_selection2').set('pos', {'100.000000' '100.000000' '-70.710678'});
model.component('component').geom('geometry').feature('bottom_outlet_selection2').set('axis', {'0.500000' '0.500000' '-0.707107'});
model.component('component').geom('geometry').feature('bottom_outlet_selection2').set('condition', 'allvertices');
model.component('component').geom('geometry').create('bottom_inlet_selection2', 'CylinderSelection');
model.component('component').geom('geometry').feature('bottom_inlet_selection2').label('Bottom Inlet Selection 2');
model.component('component').geom('geometry').feature('bottom_inlet_selection2').set('entitydim', 2);
model.component('component').geom('geometry').feature('bottom_inlet_selection2').set('r', 0.051000000000000004);
model.component('component').geom('geometry').feature('bottom_inlet_selection2').set('rin', '0');
model.component('component').geom('geometry').feature('bottom_inlet_selection2').set('top', 0.001);
model.component('component').geom('geometry').feature('bottom_inlet_selection2').set('bottom', -0.001);
model.component('component').geom('geometry').feature('bottom_inlet_selection2').set('pos', {'100.000000' '100.000000' '-70.710678'});
model.component('component').geom('geometry').feature('bottom_inlet_selection2').set('axis', {'0.500000' '0.500000' '-0.707107'});
model.component('component').geom('geometry').feature('bottom_inlet_selection2').set('condition', 'allvertices');

model.component('component').mesh('mesh').create('inner_cap_mesh2', 'FreeTri');
model.component('component').mesh('mesh').feature('inner_cap_mesh2').label('Inner Cap Mesh 2');
model.component('component').mesh('mesh').feature('inner_cap_mesh2').selection.named('geometry_inner_cap_selection2');
model.component('component').mesh('mesh').feature('inner_cap_mesh2').create('size', 'Size');
model.component('component').mesh('mesh').feature('inner_cap_mesh2').feature('size').set('hauto', 1);
model.component('component').mesh('mesh').feature('inner_cap_mesh2').feature('size').set('custom', true);
model.component('component').mesh('mesh').feature('inner_cap_mesh2').feature('size').set('hmax', 0.015);
model.component('component').mesh('mesh').feature('inner_cap_mesh2').feature('size').set('hmaxactive', true);
model.component('component').mesh('mesh').create('outer_cap_mesh2', 'FreeTri');
model.component('component').mesh('mesh').feature('outer_cap_mesh2').label('Outer Cap Mesh 2');
model.component('component').mesh('mesh').feature('outer_cap_mesh2').selection.named('geometry_outer_cap_selection2');
model.component('component').mesh('mesh').feature('outer_cap_mesh2').create('size', 'Size');
model.component('component').mesh('mesh').feature('outer_cap_mesh2').feature('size').set('hauto', 1);
model.component('component').mesh('mesh').feature('outer_cap_mesh2').feature('size').set('custom', 'on');
model.component('component').mesh('mesh').feature('outer_cap_mesh2').feature('size').set('hgrad', 1.2);
model.component('component').mesh('mesh').feature('outer_cap_mesh2').feature('size').set('hgradactive', true);
model.component('component').mesh('mesh').feature('outer_cap_mesh2').feature('size').set('hmax', 0.1);
model.component('component').mesh('mesh').feature('outer_cap_mesh2').feature('size').set('hmaxactive', true);
model.component('component').mesh('mesh').create('swept_mesh2', 'Sweep');
model.component('component').mesh('mesh').feature('swept_mesh2').label('Swept Mesh 2');
model.component('component').mesh('mesh').feature('swept_mesh2').selection.geom('geometry', 3);
model.component('component').mesh('mesh').feature('swept_mesh2').selection.named('geometry_borehole_structure_selection2');
model.component('component').mesh('mesh').feature('swept_mesh2').create('distribution', 'Distribution');
model.component('component').mesh('mesh').feature('swept_mesh2').feature('distribution').set('type', 'predefined');
model.component('component').mesh('mesh').feature('swept_mesh2').feature('distribution').set('elemcount', 300);
model.component('component').mesh('mesh').feature('swept_mesh2').feature('distribution').set('elemratio', 10);
model.component('component').mesh('mesh').feature('swept_mesh2').feature('distribution').set('symmetric', true);
model.component('component').mesh('mesh').create('cylinders_mesh2', 'FreeTet');
model.component('component').mesh('mesh').feature('cylinders_mesh2').label('Cylinders Mesh 2');
model.component('component').mesh('mesh').feature('cylinders_mesh2').selection.geom('geometry', 3);
model.component('component').mesh('mesh').feature('cylinders_mesh2').selection.named('geometry_cylinders_selection2');
model.component('component').mesh('mesh').feature('cylinders_mesh2').create('size', 'Size');
model.component('component').mesh('mesh').feature('cylinders_mesh2').feature('size').set('hauto', 3);

model.component('component').geom('geometry').create('work_plane3_borehole_structure', 'WorkPlane');
model.component('component').geom('geometry').feature('work_plane3_borehole_structure').label('Borehole Structure Work Plane 3');
model.component('component').geom('geometry').feature('work_plane3_borehole_structure').set('planetype', 'normalvector');
model.component('component').geom('geometry').feature('work_plane3_borehole_structure').set('normalcoord', {'-50.000000' '50.000000' '0.000000'});
model.component('component').geom('geometry').feature('work_plane3_borehole_structure').set('normalvector', {'-0.500000' '0.500000' '-0.707107'});
model.component('component').geom('geometry').feature('work_plane3_borehole_structure').set('unite', true);
model.component('component').geom('geometry').feature('work_plane3_borehole_structure').geom.create('circle1', 'Circle');
model.component('component').geom('geometry').feature('work_plane3_borehole_structure').geom.feature('circle1').label('Circle 1');
model.component('component').geom('geometry').feature('work_plane3_borehole_structure').geom.feature('circle1').set('r', 0.5);
model.component('component').geom('geometry').feature('work_plane3_borehole_structure').geom.create('circle2', 'Circle');
model.component('component').geom('geometry').feature('work_plane3_borehole_structure').geom.feature('circle2').label('Circle 2');
model.component('component').geom('geometry').feature('work_plane3_borehole_structure').geom.feature('circle2').set('r', 0.1);
model.component('component').geom('geometry').feature('work_plane3_borehole_structure').geom.create('circle3', 'Circle');
model.component('component').geom('geometry').feature('work_plane3_borehole_structure').geom.feature('circle3').label('Circle 3');
model.component('component').geom('geometry').feature('work_plane3_borehole_structure').geom.feature('circle3').set('r', 0.08);
model.component('component').geom('geometry').feature('work_plane3_borehole_structure').geom.create('circle4', 'Circle');
model.component('component').geom('geometry').feature('work_plane3_borehole_structure').geom.feature('circle4').label('Circle 4');
model.component('component').geom('geometry').feature('work_plane3_borehole_structure').geom.feature('circle4').set('r', 0.05);
model.component('component').geom('geometry').create('buffer_zone_selection3', 'CylinderSelection');
model.component('component').geom('geometry').feature('buffer_zone_selection3').label('Buffer Zone Selection 3');
model.component('component').geom('geometry').feature('buffer_zone_selection3').set('r', 0.501);
model.component('component').geom('geometry').feature('buffer_zone_selection3').set('rin', 0.099);
model.component('component').geom('geometry').feature('buffer_zone_selection3').set('top', 100.001);
model.component('component').geom('geometry').feature('buffer_zone_selection3').set('bottom', -0.001);
model.component('component').geom('geometry').feature('buffer_zone_selection3').set('pos', {'-50.000000' '50.000000' '0.000000'});
model.component('component').geom('geometry').feature('buffer_zone_selection3').set('axis', {'-0.500000' '0.500000' '-0.707107'});
model.component('component').geom('geometry').feature('buffer_zone_selection3').set('condition', 'allvertices');
model.component('component').geom('geometry').create('outer_fluid_selection3', 'CylinderSelection');
model.component('component').geom('geometry').feature('outer_fluid_selection3').label('Outer Fluid Selection 3');
model.component('component').geom('geometry').feature('outer_fluid_selection3').set('r', 0.101);
model.component('component').geom('geometry').feature('outer_fluid_selection3').set('rin', 0.079);
model.component('component').geom('geometry').feature('outer_fluid_selection3').set('top', 100.001);
model.component('component').geom('geometry').feature('outer_fluid_selection3').set('bottom', -0.001);
model.component('component').geom('geometry').feature('outer_fluid_selection3').set('pos', {'-50.000000' '50.000000' '0.000000'});
model.component('component').geom('geometry').feature('outer_fluid_selection3').set('axis', {'-0.500000' '0.500000' '-0.707107'});
model.component('component').geom('geometry').feature('outer_fluid_selection3').set('condition', 'allvertices');
model.component('component').geom('geometry').create('pipe_wall_selection3', 'CylinderSelection');
model.component('component').geom('geometry').feature('pipe_wall_selection3').label('Pipe Wall Selection 3');
model.component('component').geom('geometry').feature('pipe_wall_selection3').set('r', 0.081);
model.component('component').geom('geometry').feature('pipe_wall_selection3').set('rin', 0.001);
model.component('component').geom('geometry').feature('pipe_wall_selection3').set('top', 100.001);
model.component('component').geom('geometry').feature('pipe_wall_selection3').set('bottom', -0.001);
model.component('component').geom('geometry').feature('pipe_wall_selection3').set('pos', {'-50.000000' '50.000000' '0.000000'});
model.component('component').geom('geometry').feature('pipe_wall_selection3').set('axis', {'-0.500000' '0.500000' '-0.707107'});
model.component('component').geom('geometry').feature('pipe_wall_selection3').set('condition', 'inside');
model.component('component').geom('geometry').create('inner_fluid_selection3', 'CylinderSelection');
model.component('component').geom('geometry').feature('inner_fluid_selection3').label('Inner Fluid Selection 3');
model.component('component').geom('geometry').feature('inner_fluid_selection3').set('r', 0.051000000000000004);
model.component('component').geom('geometry').feature('inner_fluid_selection3').set('rin', '0');
model.component('component').geom('geometry').feature('inner_fluid_selection3').set('top', 100.001);
model.component('component').geom('geometry').feature('inner_fluid_selection3').set('bottom', -0.001);
model.component('component').geom('geometry').feature('inner_fluid_selection3').set('pos', {'-50.000000' '50.000000' '0.000000'});
model.component('component').geom('geometry').feature('inner_fluid_selection3').set('axis', {'-0.500000' '0.500000' '-0.707107'});
model.component('component').geom('geometry').feature('inner_fluid_selection3').set('condition', 'allvertices');
model.component('component').geom('geometry').create('borehole_structure_selection3', 'UnionSelection');
model.component('component').geom('geometry').feature('borehole_structure_selection3').set('input', {'buffer_zone_selection3' 'outer_fluid_selection3' 'pipe_wall_selection3' 'inner_fluid_selection3'});
model.component('component').geom('geometry').create('borehole_wall_selection3', 'CylinderSelection');
model.component('component').geom('geometry').feature('borehole_wall_selection3').label('Borehole Wall Selection 3');
model.component('component').geom('geometry').feature('borehole_wall_selection3').set('entitydim', 2);
model.component('component').geom('geometry').feature('borehole_wall_selection3').set('r', 0.101);
model.component('component').geom('geometry').feature('borehole_wall_selection3').set('rin', 0.099);
model.component('component').geom('geometry').feature('borehole_wall_selection3').set('top', 100.001);
model.component('component').geom('geometry').feature('borehole_wall_selection3').set('bottom', -0.001);
model.component('component').geom('geometry').feature('borehole_wall_selection3').set('pos', {'-50.000000' '50.000000' '0.000000'});
model.component('component').geom('geometry').feature('borehole_wall_selection3').set('axis', {'-0.500000' '0.500000' '-0.707107'});
model.component('component').geom('geometry').feature('borehole_wall_selection3').set('condition', 'allvertices');
model.component('component').geom('geometry').create('upper_cylinder_selection3', 'CylinderSelection');
model.component('component').geom('geometry').feature('upper_cylinder_selection3').label('Upper Cylinder Selection 3');
model.component('component').geom('geometry').feature('upper_cylinder_selection3').set('r', 0.501);
model.component('component').geom('geometry').feature('upper_cylinder_selection3').set('rin', '0');
model.component('component').geom('geometry').feature('upper_cylinder_selection3').set('top', 0.501);
model.component('component').geom('geometry').feature('upper_cylinder_selection3').set('bottom', -0.001);
model.component('component').geom('geometry').feature('upper_cylinder_selection3').set('pos', {'-49.750000' '49.750000' '0.353553'});
model.component('component').geom('geometry').feature('upper_cylinder_selection3').set('axis', {'-0.500000' '0.500000' '-0.707107'});
model.component('component').geom('geometry').feature('upper_cylinder_selection3').set('condition', 'allvertices');
model.component('component').geom('geometry').create('lower_cylinder_selection3', 'CylinderSelection');
model.component('component').geom('geometry').feature('lower_cylinder_selection3').label('Lower Cylinder Selection 3');
model.component('component').geom('geometry').feature('lower_cylinder_selection3').set('r', 0.501);
model.component('component').geom('geometry').feature('lower_cylinder_selection3').set('rin', '0');
model.component('component').geom('geometry').feature('lower_cylinder_selection3').set('top', 0.501);
model.component('component').geom('geometry').feature('lower_cylinder_selection3').set('bottom', -0.001);
model.component('component').geom('geometry').feature('lower_cylinder_selection3').set('pos', {'-100.000000' '100.000000' '-70.710678'});
model.component('component').geom('geometry').feature('lower_cylinder_selection3').set('axis', {'-0.500000' '0.500000' '-0.707107'});
model.component('component').geom('geometry').feature('lower_cylinder_selection3').set('condition', 'allvertices');
model.component('component').geom('geometry').create('cylinders_selection3', 'UnionSelection');
model.component('component').geom('geometry').feature('cylinders_selection3').set('input', {'upper_cylinder_selection3' 'lower_cylinder_selection3'});
model.component('component').geom('geometry').create('outer_cap_selection3', 'CylinderSelection');
model.component('component').geom('geometry').feature('outer_cap_selection3').label('Outer Cap Selection 3');
model.component('component').geom('geometry').feature('outer_cap_selection3').set('entitydim', 2);
model.component('component').geom('geometry').feature('outer_cap_selection3').set('r', 0.501);
model.component('component').geom('geometry').feature('outer_cap_selection3').set('rin', 0.099);
model.component('component').geom('geometry').feature('outer_cap_selection3').set('top', 0.001);
model.component('component').geom('geometry').feature('outer_cap_selection3').set('bottom', -0.001);
model.component('component').geom('geometry').feature('outer_cap_selection3').set('pos', {'-50.000000' '50.000000' '0.000000'});
model.component('component').geom('geometry').feature('outer_cap_selection3').set('axis', {'-0.500000' '0.500000' '-0.707107'});
model.component('component').geom('geometry').feature('outer_cap_selection3').set('condition', 'inside');
model.component('component').geom('geometry').create('inner_cap_selection3', 'CylinderSelection');
model.component('component').geom('geometry').feature('inner_cap_selection3').label('Inner Cap Selection 3');
model.component('component').geom('geometry').feature('inner_cap_selection3').set('entitydim', 2);
model.component('component').geom('geometry').feature('inner_cap_selection3').set('r', 0.101);
model.component('component').geom('geometry').feature('inner_cap_selection3').set('rin', 0);
model.component('component').geom('geometry').feature('inner_cap_selection3').set('top', 0.001);
model.component('component').geom('geometry').feature('inner_cap_selection3').set('bottom', -0.001);
model.component('component').geom('geometry').feature('inner_cap_selection3').set('pos', {'-50.000000' '50.000000' '0.000000'});
model.component('component').geom('geometry').feature('inner_cap_selection3').set('axis', {'-0.500000' '0.500000' '-0.707107'});
model.component('component').geom('geometry').feature('inner_cap_selection3').set('condition', 'allvertices');
model.component('component').geom('geometry').create('top_inlet_selection3', 'CylinderSelection');
model.component('component').geom('geometry').feature('top_inlet_selection3').label('Top Inlet Selection 3');
model.component('component').geom('geometry').feature('top_inlet_selection3').set('entitydim', 2);
model.component('component').geom('geometry').feature('top_inlet_selection3').set('r', 0.101);
model.component('component').geom('geometry').feature('top_inlet_selection3').set('rin', 0.079);
model.component('component').geom('geometry').feature('top_inlet_selection3').set('top', 0.001);
model.component('component').geom('geometry').feature('top_inlet_selection3').set('bottom', -0.001);
model.component('component').geom('geometry').feature('top_inlet_selection3').set('pos', {'-50.000000' '50.000000' '0.000000'});
model.component('component').geom('geometry').feature('top_inlet_selection3').set('axis', {'-0.500000' '0.500000' '-0.707107'});
model.component('component').geom('geometry').feature('top_inlet_selection3').set('condition', 'allvertices');
model.component('component').geom('geometry').create('top_outlet_selection3', 'CylinderSelection');
model.component('component').geom('geometry').feature('top_outlet_selection3').label('Top Outlet Selection 3');
model.component('component').geom('geometry').feature('top_outlet_selection3').set('entitydim', 2);
model.component('component').geom('geometry').feature('top_outlet_selection3').set('r', 0.051000000000000004);
model.component('component').geom('geometry').feature('top_outlet_selection3').set('rin', '0');
model.component('component').geom('geometry').feature('top_outlet_selection3').set('top', 0.001);
model.component('component').geom('geometry').feature('top_outlet_selection3').set('bottom', -0.001);
model.component('component').geom('geometry').feature('top_outlet_selection3').set('pos', {'-50.000000' '50.000000' '0.000000'});
model.component('component').geom('geometry').feature('top_outlet_selection3').set('axis', {'-0.500000' '0.500000' '-0.707107'});
model.component('component').geom('geometry').feature('top_outlet_selection3').set('condition', 'allvertices');
model.component('component').geom('geometry').create('bottom_outlet_selection3', 'CylinderSelection');
model.component('component').geom('geometry').feature('bottom_outlet_selection3').label('Bottom Outlet Selection 3');
model.component('component').geom('geometry').feature('bottom_outlet_selection3').set('entitydim', 2);
model.component('component').geom('geometry').feature('bottom_outlet_selection3').set('r', 0.101);
model.component('component').geom('geometry').feature('bottom_outlet_selection3').set('rin', 0.079);
model.component('component').geom('geometry').feature('bottom_outlet_selection3').set('top', 0.001);
model.component('component').geom('geometry').feature('bottom_outlet_selection3').set('bottom', -0.001);
model.component('component').geom('geometry').feature('bottom_outlet_selection3').set('pos', {'-100.000000' '100.000000' '-70.710678'});
model.component('component').geom('geometry').feature('bottom_outlet_selection3').set('axis', {'-0.500000' '0.500000' '-0.707107'});
model.component('component').geom('geometry').feature('bottom_outlet_selection3').set('condition', 'allvertices');
model.component('component').geom('geometry').create('bottom_inlet_selection3', 'CylinderSelection');
model.component('component').geom('geometry').feature('bottom_inlet_selection3').label('Bottom Inlet Selection 3');
model.component('component').geom('geometry').feature('bottom_inlet_selection3').set('entitydim', 2);
model.component('component').geom('geometry').feature('bottom_inlet_selection3').set('r', 0.051000000000000004);
model.component('component').geom('geometry').feature('bottom_inlet_selection3').set('rin', '0');
model.component('component').geom('geometry').feature('bottom_inlet_selection3').set('top', 0.001);
model.component('component').geom('geometry').feature('bottom_inlet_selection3').set('bottom', -0.001);
model.component('component').geom('geometry').feature('bottom_inlet_selection3').set('pos', {'-100.000000' '100.000000' '-70.710678'});
model.component('component').geom('geometry').feature('bottom_inlet_selection3').set('axis', {'-0.500000' '0.500000' '-0.707107'});
model.component('component').geom('geometry').feature('bottom_inlet_selection3').set('condition', 'allvertices');

model.component('component').mesh('mesh').create('inner_cap_mesh3', 'FreeTri');
model.component('component').mesh('mesh').feature('inner_cap_mesh3').label('Inner Cap Mesh 3');
model.component('component').mesh('mesh').feature('inner_cap_mesh3').selection.named('geometry_inner_cap_selection3');
model.component('component').mesh('mesh').feature('inner_cap_mesh3').create('size', 'Size');
model.component('component').mesh('mesh').feature('inner_cap_mesh3').feature('size').set('hauto', 1);
model.component('component').mesh('mesh').feature('inner_cap_mesh3').feature('size').set('custom', true);
model.component('component').mesh('mesh').feature('inner_cap_mesh3').feature('size').set('hmax', 0.015);
model.component('component').mesh('mesh').feature('inner_cap_mesh3').feature('size').set('hmaxactive', true);
model.component('component').mesh('mesh').create('outer_cap_mesh3', 'FreeTri');
model.component('component').mesh('mesh').feature('outer_cap_mesh3').label('Outer Cap Mesh 3');
model.component('component').mesh('mesh').feature('outer_cap_mesh3').selection.named('geometry_outer_cap_selection3');
model.component('component').mesh('mesh').feature('outer_cap_mesh3').create('size', 'Size');
model.component('component').mesh('mesh').feature('outer_cap_mesh3').feature('size').set('hauto', 1);
model.component('component').mesh('mesh').feature('outer_cap_mesh3').feature('size').set('custom', 'on');
model.component('component').mesh('mesh').feature('outer_cap_mesh3').feature('size').set('hgrad', 1.2);
model.component('component').mesh('mesh').feature('outer_cap_mesh3').feature('size').set('hgradactive', true);
model.component('component').mesh('mesh').feature('outer_cap_mesh3').feature('size').set('hmax', 0.1);
model.component('component').mesh('mesh').feature('outer_cap_mesh3').feature('size').set('hmaxactive', true);
model.component('component').mesh('mesh').create('swept_mesh3', 'Sweep');
model.component('component').mesh('mesh').feature('swept_mesh3').label('Swept Mesh 3');
model.component('component').mesh('mesh').feature('swept_mesh3').selection.geom('geometry', 3);
model.component('component').mesh('mesh').feature('swept_mesh3').selection.named('geometry_borehole_structure_selection3');
model.component('component').mesh('mesh').feature('swept_mesh3').create('distribution', 'Distribution');
model.component('component').mesh('mesh').feature('swept_mesh3').feature('distribution').set('type', 'predefined');
model.component('component').mesh('mesh').feature('swept_mesh3').feature('distribution').set('elemcount', 300);
model.component('component').mesh('mesh').feature('swept_mesh3').feature('distribution').set('elemratio', 10);
model.component('component').mesh('mesh').feature('swept_mesh3').feature('distribution').set('symmetric', true);
model.component('component').mesh('mesh').create('cylinders_mesh3', 'FreeTet');
model.component('component').mesh('mesh').feature('cylinders_mesh3').label('Cylinders Mesh 3');
model.component('component').mesh('mesh').feature('cylinders_mesh3').selection.geom('geometry', 3);
model.component('component').mesh('mesh').feature('cylinders_mesh3').selection.named('geometry_cylinders_selection3');
model.component('component').mesh('mesh').feature('cylinders_mesh3').create('size', 'Size');
model.component('component').mesh('mesh').feature('cylinders_mesh3').feature('size').set('hauto', 3);

model.component('component').geom('geometry').create('work_plane4_borehole_structure', 'WorkPlane');
model.component('component').geom('geometry').feature('work_plane4_borehole_structure').label('Borehole Structure Work Plane 4');
model.component('component').geom('geometry').feature('work_plane4_borehole_structure').set('planetype', 'normalvector');
model.component('component').geom('geometry').feature('work_plane4_borehole_structure').set('normalcoord', {'-50.000000' '-50.000000' '-50.000000'});
model.component('component').geom('geometry').feature('work_plane4_borehole_structure').set('normalvector', {'-0.500000' '-0.500000' '-0.707107'});
model.component('component').geom('geometry').feature('work_plane4_borehole_structure').set('unite', true);
model.component('component').geom('geometry').feature('work_plane4_borehole_structure').geom.create('circle1', 'Circle');
model.component('component').geom('geometry').feature('work_plane4_borehole_structure').geom.feature('circle1').label('Circle 1');
model.component('component').geom('geometry').feature('work_plane4_borehole_structure').geom.feature('circle1').set('r', 0.5);
model.component('component').geom('geometry').feature('work_plane4_borehole_structure').geom.create('circle2', 'Circle');
model.component('component').geom('geometry').feature('work_plane4_borehole_structure').geom.feature('circle2').label('Circle 2');
model.component('component').geom('geometry').feature('work_plane4_borehole_structure').geom.feature('circle2').set('r', 0.1);
model.component('component').geom('geometry').feature('work_plane4_borehole_structure').geom.create('circle3', 'Circle');
model.component('component').geom('geometry').feature('work_plane4_borehole_structure').geom.feature('circle3').label('Circle 3');
model.component('component').geom('geometry').feature('work_plane4_borehole_structure').geom.feature('circle3').set('r', 0.08);
model.component('component').geom('geometry').feature('work_plane4_borehole_structure').geom.create('circle4', 'Circle');
model.component('component').geom('geometry').feature('work_plane4_borehole_structure').geom.feature('circle4').label('Circle 4');
model.component('component').geom('geometry').feature('work_plane4_borehole_structure').geom.feature('circle4').set('r', 0.05);
model.component('component').geom('geometry').feature('work_plane4_borehole_structure').geom.create('polygon1', 'Polygon');
model.component('component').geom('geometry').feature('work_plane4_borehole_structure').geom.feature('polygon1').set('source', 'table');
model.component('component').geom('geometry').feature('work_plane4_borehole_structure').geom.feature('polygon1').set('table', {'-0.353553' '-0.353553'; '-0.707107' '0.000000'; '0.000000' '0.707107'; '0.353553' '0.353553'});
model.component('component').geom('geometry').feature('work_plane4_borehole_structure').geom.create('polygon2', 'Polygon');
model.component('component').geom('geometry').feature('work_plane4_borehole_structure').geom.feature('polygon2').set('source', 'table');
model.component('component').geom('geometry').feature('work_plane4_borehole_structure').geom.feature('polygon2').set('table', {'0.500000' '0.000000'; '0.500000' '-0.500000'; '-0.500000' '-0.500000'; '-0.500000' '-0.000000'});
model.component('component').geom('geometry').create('buffer_zone_selection4', 'CylinderSelection');
model.component('component').geom('geometry').feature('buffer_zone_selection4').label('Buffer Zone Selection 4');
model.component('component').geom('geometry').feature('buffer_zone_selection4').set('r', 0.501);
model.component('component').geom('geometry').feature('buffer_zone_selection4').set('rin', 0.099);
model.component('component').geom('geometry').feature('buffer_zone_selection4').set('top', 100.001);
model.component('component').geom('geometry').feature('buffer_zone_selection4').set('bottom', -0.001);
model.component('component').geom('geometry').feature('buffer_zone_selection4').set('pos', {'-50.000000' '-50.000000' '-50.000000'});
model.component('component').geom('geometry').feature('buffer_zone_selection4').set('axis', {'-0.500000' '-0.500000' '-0.707107'});
model.component('component').geom('geometry').feature('buffer_zone_selection4').set('condition', 'allvertices');
model.component('component').geom('geometry').create('outer_fluid_selection4', 'CylinderSelection');
model.component('component').geom('geometry').feature('outer_fluid_selection4').label('Outer Fluid Selection 4');
model.component('component').geom('geometry').feature('outer_fluid_selection4').set('r', 0.101);
model.component('component').geom('geometry').feature('outer_fluid_selection4').set('rin', 0.079);
model.component('component').geom('geometry').feature('outer_fluid_selection4').set('top', 100.001);
model.component('component').geom('geometry').feature('outer_fluid_selection4').set('bottom', -0.001);
model.component('component').geom('geometry').feature('outer_fluid_selection4').set('pos', {'-50.000000' '-50.000000' '-50.000000'});
model.component('component').geom('geometry').feature('outer_fluid_selection4').set('axis', {'-0.500000' '-0.500000' '-0.707107'});
model.component('component').geom('geometry').feature('outer_fluid_selection4').set('condition', 'allvertices');
model.component('component').geom('geometry').create('pipe_wall_selection4', 'CylinderSelection');
model.component('component').geom('geometry').feature('pipe_wall_selection4').label('Pipe Wall Selection 4');
model.component('component').geom('geometry').feature('pipe_wall_selection4').set('r', 0.081);
model.component('component').geom('geometry').feature('pipe_wall_selection4').set('rin', 0.001);
model.component('component').geom('geometry').feature('pipe_wall_selection4').set('top', 100.001);
model.component('component').geom('geometry').feature('pipe_wall_selection4').set('bottom', -0.001);
model.component('component').geom('geometry').feature('pipe_wall_selection4').set('pos', {'-50.000000' '-50.000000' '-50.000000'});
model.component('component').geom('geometry').feature('pipe_wall_selection4').set('axis', {'-0.500000' '-0.500000' '-0.707107'});
model.component('component').geom('geometry').feature('pipe_wall_selection4').set('condition', 'inside');
model.component('component').geom('geometry').create('inner_fluid_selection4', 'CylinderSelection');
model.component('component').geom('geometry').feature('inner_fluid_selection4').label('Inner Fluid Selection 4');
model.component('component').geom('geometry').feature('inner_fluid_selection4').set('r', 0.051000000000000004);
model.component('component').geom('geometry').feature('inner_fluid_selection4').set('rin', '0');
model.component('component').geom('geometry').feature('inner_fluid_selection4').set('top', 100.001);
model.component('component').geom('geometry').feature('inner_fluid_selection4').set('bottom', -0.001);
model.component('component').geom('geometry').feature('inner_fluid_selection4').set('pos', {'-50.000000' '-50.000000' '-50.000000'});
model.component('component').geom('geometry').feature('inner_fluid_selection4').set('axis', {'-0.500000' '-0.500000' '-0.707107'});
model.component('component').geom('geometry').feature('inner_fluid_selection4').set('condition', 'allvertices');
model.component('component').geom('geometry').create('borehole_structure_selection4', 'UnionSelection');
model.component('component').geom('geometry').feature('borehole_structure_selection4').set('input', {'buffer_zone_selection4' 'outer_fluid_selection4' 'pipe_wall_selection4' 'inner_fluid_selection4'});
model.component('component').geom('geometry').create('borehole_wall_selection4', 'CylinderSelection');
model.component('component').geom('geometry').feature('borehole_wall_selection4').label('Borehole Wall Selection 4');
model.component('component').geom('geometry').feature('borehole_wall_selection4').set('entitydim', 2);
model.component('component').geom('geometry').feature('borehole_wall_selection4').set('r', 0.101);
model.component('component').geom('geometry').feature('borehole_wall_selection4').set('rin', 0.099);
model.component('component').geom('geometry').feature('borehole_wall_selection4').set('top', 100.001);
model.component('component').geom('geometry').feature('borehole_wall_selection4').set('bottom', -0.001);
model.component('component').geom('geometry').feature('borehole_wall_selection4').set('pos', {'-50.000000' '-50.000000' '-50.000000'});
model.component('component').geom('geometry').feature('borehole_wall_selection4').set('axis', {'-0.500000' '-0.500000' '-0.707107'});
model.component('component').geom('geometry').feature('borehole_wall_selection4').set('condition', 'allvertices');
model.component('component').geom('geometry').create('upper_cylinder_selection4', 'CylinderSelection');
model.component('component').geom('geometry').feature('upper_cylinder_selection4').label('Upper Cylinder Selection 4');
model.component('component').geom('geometry').feature('upper_cylinder_selection4').set('r', 0.501);
model.component('component').geom('geometry').feature('upper_cylinder_selection4').set('rin', '0');
model.component('component').geom('geometry').feature('upper_cylinder_selection4').set('top', 0.501);
model.component('component').geom('geometry').feature('upper_cylinder_selection4').set('bottom', -0.001);
model.component('component').geom('geometry').feature('upper_cylinder_selection4').set('pos', {'-49.750000' '-49.750000' '-49.646447'});
model.component('component').geom('geometry').feature('upper_cylinder_selection4').set('axis', {'-0.500000' '-0.500000' '-0.707107'});
model.component('component').geom('geometry').feature('upper_cylinder_selection4').set('condition', 'allvertices');
model.component('component').geom('geometry').create('lower_cylinder_selection4', 'CylinderSelection');
model.component('component').geom('geometry').feature('lower_cylinder_selection4').label('Lower Cylinder Selection 4');
model.component('component').geom('geometry').feature('lower_cylinder_selection4').set('r', 0.501);
model.component('component').geom('geometry').feature('lower_cylinder_selection4').set('rin', '0');
model.component('component').geom('geometry').feature('lower_cylinder_selection4').set('top', 0.501);
model.component('component').geom('geometry').feature('lower_cylinder_selection4').set('bottom', -0.001);
model.component('component').geom('geometry').feature('lower_cylinder_selection4').set('pos', {'-100.000000' '-100.000000' '-120.710678'});
model.component('component').geom('geometry').feature('lower_cylinder_selection4').set('axis', {'-0.500000' '-0.500000' '-0.707107'});
model.component('component').geom('geometry').feature('lower_cylinder_selection4').set('condition', 'allvertices');
model.component('component').geom('geometry').create('cylinders_selection4', 'UnionSelection');
model.component('component').geom('geometry').feature('cylinders_selection4').set('input', {'upper_cylinder_selection4' 'lower_cylinder_selection4'});
model.component('component').geom('geometry').create('outer_cap_selection4', 'CylinderSelection');
model.component('component').geom('geometry').feature('outer_cap_selection4').label('Outer Cap Selection 4');
model.component('component').geom('geometry').feature('outer_cap_selection4').set('entitydim', 2);
model.component('component').geom('geometry').feature('outer_cap_selection4').set('r', 0.501);
model.component('component').geom('geometry').feature('outer_cap_selection4').set('rin', 0.099);
model.component('component').geom('geometry').feature('outer_cap_selection4').set('top', 0.001);
model.component('component').geom('geometry').feature('outer_cap_selection4').set('bottom', -0.001);
model.component('component').geom('geometry').feature('outer_cap_selection4').set('pos', {'-50.000000' '-50.000000' '-50.000000'});
model.component('component').geom('geometry').feature('outer_cap_selection4').set('axis', {'-0.500000' '-0.500000' '-0.707107'});
model.component('component').geom('geometry').feature('outer_cap_selection4').set('condition', 'inside');
model.component('component').geom('geometry').create('inner_cap_selection4', 'CylinderSelection');
model.component('component').geom('geometry').feature('inner_cap_selection4').label('Inner Cap Selection 4');
model.component('component').geom('geometry').feature('inner_cap_selection4').set('entitydim', 2);
model.component('component').geom('geometry').feature('inner_cap_selection4').set('r', 0.101);
model.component('component').geom('geometry').feature('inner_cap_selection4').set('rin', 0);
model.component('component').geom('geometry').feature('inner_cap_selection4').set('top', 0.001);
model.component('component').geom('geometry').feature('inner_cap_selection4').set('bottom', -0.001);
model.component('component').geom('geometry').feature('inner_cap_selection4').set('pos', {'-50.000000' '-50.000000' '-50.000000'});
model.component('component').geom('geometry').feature('inner_cap_selection4').set('axis', {'-0.500000' '-0.500000' '-0.707107'});
model.component('component').geom('geometry').feature('inner_cap_selection4').set('condition', 'allvertices');
model.component('component').geom('geometry').create('top_inlet_selection4', 'CylinderSelection');
model.component('component').geom('geometry').feature('top_inlet_selection4').label('Top Inlet Selection 4');
model.component('component').geom('geometry').feature('top_inlet_selection4').set('entitydim', 2);
model.component('component').geom('geometry').feature('top_inlet_selection4').set('r', 0.101);
model.component('component').geom('geometry').feature('top_inlet_selection4').set('rin', 0.079);
model.component('component').geom('geometry').feature('top_inlet_selection4').set('top', 0.001);
model.component('component').geom('geometry').feature('top_inlet_selection4').set('bottom', -0.001);
model.component('component').geom('geometry').feature('top_inlet_selection4').set('pos', {'-50.000000' '-50.000000' '-50.000000'});
model.component('component').geom('geometry').feature('top_inlet_selection4').set('axis', {'-0.500000' '-0.500000' '-0.707107'});
model.component('component').geom('geometry').feature('top_inlet_selection4').set('condition', 'allvertices');
model.component('component').geom('geometry').create('top_outlet_selection4', 'CylinderSelection');
model.component('component').geom('geometry').feature('top_outlet_selection4').label('Top Outlet Selection 4');
model.component('component').geom('geometry').feature('top_outlet_selection4').set('entitydim', 2);
model.component('component').geom('geometry').feature('top_outlet_selection4').set('r', 0.051000000000000004);
model.component('component').geom('geometry').feature('top_outlet_selection4').set('rin', '0');
model.component('component').geom('geometry').feature('top_outlet_selection4').set('top', 0.001);
model.component('component').geom('geometry').feature('top_outlet_selection4').set('bottom', -0.001);
model.component('component').geom('geometry').feature('top_outlet_selection4').set('pos', {'-50.000000' '-50.000000' '-50.000000'});
model.component('component').geom('geometry').feature('top_outlet_selection4').set('axis', {'-0.500000' '-0.500000' '-0.707107'});
model.component('component').geom('geometry').feature('top_outlet_selection4').set('condition', 'allvertices');
model.component('component').geom('geometry').create('bottom_outlet_selection4', 'CylinderSelection');
model.component('component').geom('geometry').feature('bottom_outlet_selection4').label('Bottom Outlet Selection 4');
model.component('component').geom('geometry').feature('bottom_outlet_selection4').set('entitydim', 2);
model.component('component').geom('geometry').feature('bottom_outlet_selection4').set('r', 0.101);
model.component('component').geom('geometry').feature('bottom_outlet_selection4').set('rin', 0.079);
model.component('component').geom('geometry').feature('bottom_outlet_selection4').set('top', 0.001);
model.component('component').geom('geometry').feature('bottom_outlet_selection4').set('bottom', -0.001);
model.component('component').geom('geometry').feature('bottom_outlet_selection4').set('pos', {'-100.000000' '-100.000000' '-120.710678'});
model.component('component').geom('geometry').feature('bottom_outlet_selection4').set('axis', {'-0.500000' '-0.500000' '-0.707107'});
model.component('component').geom('geometry').feature('bottom_outlet_selection4').set('condition', 'allvertices');
model.component('component').geom('geometry').create('bottom_inlet_selection4', 'CylinderSelection');
model.component('component').geom('geometry').feature('bottom_inlet_selection4').label('Bottom Inlet Selection 4');
model.component('component').geom('geometry').feature('bottom_inlet_selection4').set('entitydim', 2);
model.component('component').geom('geometry').feature('bottom_inlet_selection4').set('r', 0.051000000000000004);
model.component('component').geom('geometry').feature('bottom_inlet_selection4').set('rin', '0');
model.component('component').geom('geometry').feature('bottom_inlet_selection4').set('top', 0.001);
model.component('component').geom('geometry').feature('bottom_inlet_selection4').set('bottom', -0.001);
model.component('component').geom('geometry').feature('bottom_inlet_selection4').set('pos', {'-100.000000' '-100.000000' '-120.710678'});
model.component('component').geom('geometry').feature('bottom_inlet_selection4').set('axis', {'-0.500000' '-0.500000' '-0.707107'});
model.component('component').geom('geometry').feature('bottom_inlet_selection4').set('condition', 'allvertices');

model.component('component').mesh('mesh').create('inner_cap_mesh4', 'FreeTri');
model.component('component').mesh('mesh').feature('inner_cap_mesh4').label('Inner Cap Mesh 4');
model.component('component').mesh('mesh').feature('inner_cap_mesh4').selection.named('geometry_inner_cap_selection4');
model.component('component').mesh('mesh').feature('inner_cap_mesh4').create('size', 'Size');
model.component('component').mesh('mesh').feature('inner_cap_mesh4').feature('size').set('hauto', 1);
model.component('component').mesh('mesh').feature('inner_cap_mesh4').feature('size').set('custom', true);
model.component('component').mesh('mesh').feature('inner_cap_mesh4').feature('size').set('hmax', 0.015);
model.component('component').mesh('mesh').feature('inner_cap_mesh4').feature('size').set('hmaxactive', true);
model.component('component').mesh('mesh').create('outer_cap_mesh4', 'FreeTri');
model.component('component').mesh('mesh').feature('outer_cap_mesh4').label('Outer Cap Mesh 4');
model.component('component').mesh('mesh').feature('outer_cap_mesh4').selection.named('geometry_outer_cap_selection4');
model.component('component').mesh('mesh').feature('outer_cap_mesh4').create('size', 'Size');
model.component('component').mesh('mesh').feature('outer_cap_mesh4').feature('size').set('hauto', 1);
model.component('component').mesh('mesh').feature('outer_cap_mesh4').feature('size').set('custom', 'on');
model.component('component').mesh('mesh').feature('outer_cap_mesh4').feature('size').set('hgrad', 1.2);
model.component('component').mesh('mesh').feature('outer_cap_mesh4').feature('size').set('hgradactive', true);
model.component('component').mesh('mesh').feature('outer_cap_mesh4').feature('size').set('hmax', 0.1);
model.component('component').mesh('mesh').feature('outer_cap_mesh4').feature('size').set('hmaxactive', true);
model.component('component').mesh('mesh').create('swept_mesh4', 'Sweep');
model.component('component').mesh('mesh').feature('swept_mesh4').label('Swept Mesh 4');
model.component('component').mesh('mesh').feature('swept_mesh4').selection.geom('geometry', 3);
model.component('component').mesh('mesh').feature('swept_mesh4').selection.named('geometry_borehole_structure_selection4');
model.component('component').mesh('mesh').feature('swept_mesh4').create('distribution', 'Distribution');
model.component('component').mesh('mesh').feature('swept_mesh4').feature('distribution').set('type', 'predefined');
model.component('component').mesh('mesh').feature('swept_mesh4').feature('distribution').set('elemcount', 300);
model.component('component').mesh('mesh').feature('swept_mesh4').feature('distribution').set('elemratio', 10);
model.component('component').mesh('mesh').feature('swept_mesh4').feature('distribution').set('symmetric', true);
model.component('component').mesh('mesh').create('cylinders_mesh4', 'FreeTet');
model.component('component').mesh('mesh').feature('cylinders_mesh4').label('Cylinders Mesh 4');
model.component('component').mesh('mesh').feature('cylinders_mesh4').selection.geom('geometry', 3);
model.component('component').mesh('mesh').feature('cylinders_mesh4').selection.named('geometry_cylinders_selection4');
model.component('component').mesh('mesh').feature('cylinders_mesh4').create('size', 'Size');
model.component('component').mesh('mesh').feature('cylinders_mesh4').feature('size').set('hauto', 3);

model.label('temp.mph');

model.component('component').geom('geometry').feature('work_plane4_borehole_structure').geom.run('polygon2');
model.component('component').geom('geometry').feature('work_plane4_borehole_structure').geom.create('dif1', 'Difference');
model.component('component').geom('geometry').feature('work_plane4_borehole_structure').geom.feature('dif1').selection('input').set({'circle1' 'circle2' 'circle3' 'circle4'});
model.component('component').geom('geometry').feature('work_plane4_borehole_structure').geom.feature('dif1').selection('input2').set({'polygon1' 'polygon2'});
model.component('component').geom('geometry').feature('work_plane4_borehole_structure').geom.run('dif1');

out = model;
